### ISSUE TITLE
Feature Request: Tablet Throttler - retain/expose counter of ThrottleMetric for more flexible tablet throttling 

### ISSUE THREAD

**Issue by gedgar** [vitessio/vitess#10407]
### Feature Description
For users with sensitive latency requirements, `threads_running` works well as a throttling metric however there isn't a good 'one size fits all' value, given differing workloads across various clusters. While MySQL does expose the number of queries an instance has served since boot, we do not currently have a great way to throttle on a metric like QPS. 

Currently, Vitess doesn't expose a current counter of the ThrottlerMetric, but if we kept this value in memory and exposed it via a metric, it could be used for more flexible/custom throttling+thresholds. 

### Use Case(s)

More flexible/custom tablet throttling based on delta between current/previous value of ThrottlerMetric, eg QPS.

**Comment by shlomi-noach** [comment]
@gedgar I _believe_ https://github.com/vitessio/vitess/pull/10443 might answer this issue?

For example:

```shell
$ curl -s http://127.0.0.1:15100/debug/vars | jq . | grep throttler.aggregated
  "throttler.aggregated.mysql.self": 0.221097,
  "throttler.aggregated.mysql.shard": 0.025084,
```

these are the "self check" and "shard check" values. In this case both are configured to read replication lag, and the value is the aggregated lag on all relevant servers

- in "self check" the only relevant server is the tablet's backing MySQL (hence "self")
- in "shard check" th erelevant servers could be e.g. `REPLICA,PRIMARY`, depending on config, and the aggregated value would be the `MAX` of all.

The metrics naming are under discussion, per https://github.com/vitessio/vitess/pull/10443#issuecomment-1147854981, but does this otherwise look good to you?

**Comment by gedgar** [comment]
@shlomi-noach, [#10443](https://github.com/vitessio/vitess/pull/10443) LGTM; thank you!
