### ISSUE TITLE
Question:  Mysql 5.6 support

### ISSUE THREAD

**Issue by fisher-he** [vitessio/vitess#10801]
### Question

Is Vitess 13 or 14 compatible with MySQL 5.6?

**Comment by deepthi** [comment]
MySQL 5.6 and Percona 5.6 EOL was in Feb 2021. The upstream packages we would need in order to publish docker images etc. are no longer available.
Having said that, from a Vitess POV, there isn't much (or any) difference in how we manage MySQL 5.6 vs 5.7. The management commands are basically the same.
The pre-requisites for using various functionality (binlog_format should be ROW, binlog_image should be FULL etc.) still apply regardless of MySQL version.
You may try to run Vitess 12 or 13 with MySQL 5.6 and as long as it is configured correctly, it will probably work. However, the maintainer team will not be able to reproduce or fix any problems you may run into.

**Comment by fisher-he** [comment]
@deepthi  Got it, thanks a lot. Of course, it would be best if we could upgrade to version 5.7, but the prod environment may not allow for upgraded versions.
