### ISSUE TITLE
Bug Report: pt-online-schema-change doesn't work properly with pt-ocs 

### ISSUE THREAD

**Issue by resworld** [vitessio/vitess#11060]
### Overview of the Issue

I am trying to run liquibase with pt-online-schema-change for altering table, but facing issue that vitess can't see new table created for the alter. Using pt-osc for ddl_strategy in vtgate doesn't help.

```
desc = Table 'commerce._customer_new' doesn't exist (errno 1146)
```

### Reproduction Steps

1. Running vitess container
2. Adding following line in vtgate-up script:
```
  --ddl_strategy pt-osc \
```
3. Also additional lines in vttablet-up script:
```
 --init_db_name_override $keyspace \
 --db_app_user vt_dba \
```
4. Create DATABASECHANGELOGLOCK and DATABASECHANGELOG by adding this in create_commerce_schema.sql file:
```
CREATE TABLE `DATABASECHANGELOGLOCK` (
  `ID` int(11) NOT NULL,
  `LOCKED` bit(1) NOT NULL,
  `LOCKGRANTED` datetime DEFAULT NULL,
  `LOCKEDBY` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `DATABASECHANGELOG` (
  `ID` varchar(255) COLLATE utf8_bin NOT NULL,
  `AUTHOR` varchar(255) COLLATE utf8_bin NOT NULL,
  `FILENAME` varchar(255) COLLATE utf8_bin NOT NULL,
  `DATEEXECUTED` datetime NOT NULL,
  `ORDEREXECUTED` int(11) NOT NULL,
  `EXECTYPE` varchar(10) COLLATE utf8_bin NOT NULL,
  `MD5SUM` varchar(35) COLLATE utf8_bin DEFAULT NULL,
  `DESCRIPTION` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `COMMENTS` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `TAG` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `LIQUIBASE` varchar(20) COLLATE utf8_bin DEFAULT NULL,
  `CONTEXTS` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `LABELS` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `DEPLOYMENT_ID` varchar(10) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`ID`,`AUTHOR`,`FILENAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin ENCRYPTION='N';
```
Note: If I tried to create tables in mysql connecting via vtgate using pt-ocs it just give me an UUID but table isn't created

5. Bring cluster down and run it again:
```
./401_teardown.sh && ./101_initial_cluster.sh
```

6. Prepare patch in liquibase container:
```
<?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog
    xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext"
    xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.4.xsd
            http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd">

    <changeSet id="1" author="Veselin Zlatev" context="test">
        <comment>Add TaxType column to customer table</comment>
        <addColumn tableName="customer">
            <column name="TaxType" type="ENUM('Net','Gross')" defaultValue="Gross" afterColumn="Amount">
                <constraints nullable="false"/>
            </column>
        </addColumn>
        <rollback>
            <dropColumn tableName="customer" columnName="TaxType"/>
        </rollback>
    </changeSet>

</databaseChangeLog>
```

7. Run liquibase by using credentials for accessing the vitess container:
```
cd /tmp && LANG=en_US.UTF-8 /usr/bin/liquibase     --contexts=test     --username=vitess     --password=pass     --url=jdbc:mysql://09b87a9fc7c2:15306/commerce     --driver=com.mysql.cj.jdbc.Driver     --classpath=/usr/share/java/mysql-connector-java.jar:/liquibase/database/vitess     --changeLogFile=databaseChangeLog.xml     --defaultSchemaName=commerce     --outputDefaultSchema=true     --logLevel=info update
```

8. View error:
```
07:11:34.277 INFO  [liquibase.Liquibase]: 	(in cleanup) DBD::mysql::db selectrow_hashref failed: target: commerce.0.primary: vttablet: rpc error: code = NotFound desc = Table 'commerce._customer_new' doesn't exist (errno 1146) (sqlstate 42S02) (CallerID: userData1): Sql: "show create table _customer_new", BindVars: {} [for Statement "SHOW CREATE TABLE `commerce`.`_customer_new`"] at /usr/bin/pt-online-schema-change line 3293.
```

9. Check the vitess databases:
```
vitess@09b87a9fc7c2:/vt/local$ mysql -e "show tables ; "  | grep customer
_customer_new
customer
```

### Binary Version

```sh
vitess@09b87a9fc7c2:/vt/local$ vtgate --version
ERROR: logging before flag.Parse: E0822 07:29:26.126713   22482 syslogger.go:149] can't connect to syslog
Version: 15.0.0-SNAPSHOT (Git revision 574ac26ca6dcdc76fef9b2cc98ed6896a618aee1 branch 'main') built on Thu Aug 18 07:31:23 UTC 2022 by vitess@buildkitsandbox using go1.18.4 linux/amd64
```
```


### Operating System and Environment details

```sh
cat /etc/os-release:

PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

uname -sr
```
Linux 5.10.25-linuxkit
```

uname -m
```
x86_64
```
```


### Log Fragments

_No response_

**Comment by shlomi-noach** [comment]
Thank you, I'd like to narrow this down. Would you be able to please check the following:

Run a `pt-osc` migration directly from `vtgate`, no `liquibase` involved, like so:
```sql
set @@ddl_strategy='pt-osc';
alter table <your_table> engine=innodb;
```
and wee if it's successful?

Next, a few thoughts and notes.

> If I tried to create tables in mysql connecting via vtgate using pt-ocs it just give me an UUID but table isn't created

How long did you wait before checking for table existence? When using `ddl_strategy=pt-osc` then the tables are not created _directly_ but are submitted to the Online DDL scheduler. They may take a few seconds to run. Thus, if you issue a `CREATE TABLE` and immediately check for them -- they won't be there.
If you want to create them immediately and directly, use `set @@ddl_strategy='direct'; CREATE TABLE ...`

Next, I'm unsure how Liquibase should react here. Is Liquibase even aware of pt-osc? Asking because I don't know. The way I understand this, Liquibase issues a `ALTER TABLE` and _assumes_ that the query may take a while, that the query is blocking, and that if/when the query completes, that means the table is altered. That is not the case with Online DDL. You submit a query, and it returns immediately with a job ID. You then need to track the migration with that job ID. Liquibase probably assumes that the migration completed instantly.

I feel like we should write a Vitess plugin for Liquibase, or some other integration. I have not looked into this.

Last, I'm trying to understand the error message:

```
07:11:34.277 INFO  [liquibase.Liquibase]: 	(in cleanup) DBD::mysql::db selectrow_hashref failed: target: commerce.0.primary: vttablet: rpc error: code = NotFound desc = Table 'commerce._customer_new' doesn't exist (errno 1146) (sqlstate 42S02) (CallerID: userData1): Sql: "show create table _customer_new", BindVars: {} [for Statement "SHOW CREATE TABLE `commerce`.`_customer_new`"] at /usr/bin/pt-online-schema-change line 3293.
```

where does `[liquibase.Liquibase]` come from? And how is `/usr/bin/pt-online-schema-change line 3293` involved? It feels to me like Liquibase was trying to run `pt-online-schema-change` on top of vitess? I find this very confusing, can you please clarify?

**Comment by shlomi-noach** [comment]
I get the feeling you may be trying to run `pt-osc` via Liquibase, **and** have set `ddl_stragey=pt-osc` which means double pt-osc, and which is obviously not going to work. Awaiting further advice.

**Comment by resworld** [comment]
I don't have pt-osc in Liquibase. I've double check and nowhere is having this in the liquibase container.

**Comment by shlomi-noach** [comment]
OK, so you're trying to run Liquibase on top of vitess with `pt-osc` strategy. I suspect this will not work, for the reason I mentioned above. Liquibase expect a synchronous execution, not an asynchronous execution.

You _could_ try running Liquibase with a `pt-osc` plugin directly on the primary MySQL server, bypassing vitess.

**Comment by resworld** [comment]
Yes, when I've run the liquibase directly on the primary MySQL server it works fine, but in that approach I will need created another mysql user and always needs to find proper MySQL server is the primary one. I was expected liquibase to work via vtgate so it sends queries to the primary node properly.

**Comment by shlomi-noach** [comment]
@resworld ok, now I get it! Liquibase should work with `vtgate` - but only with `direct` strategy. If the strategy is `pt-osc` then Liquibase gets confused because the `ALTER` query returns before the table is actually modified.

On the other hand, you cannot run `pt-online-schema-change` on top of `vtgate`, because `vtgate` will not accept the trigger syntax.

So your options are:

1. Run Liquibase on vtgate with `direct` strategy
2. Run a `pt-osc` strategy `ALTER TABLE` on `vtgate, but without Liquibase
3. Run a Liquibase + pt-osc plugin migration directly on the backend MySQL server, and you need to find/create the right credentials.

**Comment by shlomi-noach** [comment]
Unless there's any more questions I'm going to close this issue; marking as "not a bug".

**Comment by resworld** [comment]
@shlomi-noach thank you for helping out on that.

1. Run Liquibase on vtgate with direct strategy
- I've tried that, but now it's failing because pt-online-schema is trying to create TRIGGER after altering the table:
```
syntax error at position 15 near 'TRIGGER' [for Statement "CREATE TRIGGER `pt_osc_commerce_ customer_del` AFTER DELETE ON `commerce`.`customer ` FOR EACH ROW BEGIN DECLARE CONTINUE HANDLER FOR 1146 begin end; DELETE IGNORE FROM `commerce`.`_ customer_new` WHERE `commerce`.`_ customer_new`.`id` <=> OLD.`id`; END "] 
```
2. Run a pt-osc strategy ALTER TABLE on `vtgate, but without Liquibase
- I don't like to run Alters without liquibase. Idea is to use patches for altering the database.
3. Run a Liquibase + pt-osc plugin migration directly on the backend MySQL server, and you need to find/create the right credentials.
- This is what we know it works fine, but I think isn't best approach to sending liquibase to the mysql server directly because we should check everytime which is the primary one

If there's no other way, we would use option 3 then...

**Comment by resworld** [comment]
I don't feel into vitess enough so I don't think I can help with writing such of adapter. I will give it a try with disabling pt-online-schema plugin in liquibase and if this doesn't work - I will use direct connection to the mysql. 
Thank you for all the help and I think this github's issue can be closed.
