### ISSUE TITLE
Feature Request: Specifying multiple TabletTypes (e.g. REPLICA,PRIMARY) during VStream client subscription.

### ISSUE THREAD

**Issue by HenryCaiHaiying** [vitessio/vitess#11579]
### Feature Description

Currently, when the client initiate a VStream subscription, we can only specify one TabletType:
vtgate.proto
  // VStreamRequest is the payload for VStream.
  message VStreamRequest {
   vtrpc.CallerID caller_id = 1;
   topodata.TabletType tablet_type = 2;

But we want to specify multiple tablet types to have the choice to fallback to a different type of tablet.  And looks like VReplication path already supports that:
https://vitess.io/docs/14.0/reference/vreplication/flags/#vreplication_tablet_type
  vreplication_tablet_type
  Default in_order:REPLICA,PRIMARY

The server side implementation is also ready: https://github.com/vitessio/vitess/blob/main/go/vt/discovery/tablet_picker.go#L170

### Use Case(s)

for VStream client (debezium) subscription, we usually specify TabletType=Replica, however in some of AZs there is only Primary tablet (no Replica tablet), we would prefer to specify multiple tablet types to enlarge the tablet selection.  Otherwise the client needs to do a relatively complex fallback/retry logic and we don't really own that client project (debezium) to modify that logic easily.

**Comment by HenryCaiHaiying** [comment]
We have semi-sync configured for our Vitess layout.  And to make sure there is at least 2 AZs gets the data, the Primary and Replica tablet are laid out in two different AZs.  And VtGate is laid out per AZ and it only knows the tablet in its own AZ.  When the debezium client connects to the VtGate in its own AZ with subscription request tabletType=Replica, that VtGate might not have a Replica tablet to match (it might only have a Primary tablet in its AZ).  In this case, we would prefer the VtGate to fall back to that Primary tablet.

**Comment by HenryCaiHaiying** [comment]
We are mostly interested in the fallback option during initial connection, not necessarily during the middle of the streaming.

**Comment by falun** [comment]
Moving some thoughts from community slack thread: With the caveat of not having looked at the VStream code in a long time I _thought_ that being able to pick tablets across cells was resolved with https://github.com/vitessio/vitess/pull/6442. It's feasible that that code isn't in the vstream tablet selection path though?

If not it may be a fast & "easy" fix to solve the underlying problem which (seems to be?) "can't select tablet type that isn't in vtgate's cell" in addition to adding the ability to have fallback tablet type selectable.

**Comment by HenryCaiHaiying** [comment]
I think this is the tablet picker used in vstream code: https://github.com/vitessio/vitess/blob/main/go/vt/discovery/tablet_picker.go#L170.

The client might not necessarily want an across cell tablet picker since across-cell network communication cost money.

**Comment by falun** [comment]
> The client might not necessarily want an across cell tablet picker since across-cell network communication cost money.

While I agree that you may pay additional costs for this it feels like a bug/correctness concern in requiring the client to understand the cell topology when connecting to a vtgate.

There is a kind of parallel here to usage of `@replica` or `@primary` to pin queries to a specific tablet type -- if we issue a tablet-pinned query to a vtgate that doesn't share a cell of that type it should not (and doesn't!) fail to route the query. Instead it finds an appropriate tablet and serves the request.

Anyway, it's reasonable for us to say that there is a request: "allow fallbacks to other tablet types" _and_ a surprising behavior/bug around "VStream subscription should function across cells." As we go forward on this feature request is it feasible to make the cross-cell support a requirement for the implementation, @mattlord? Alternatively we could possibly split that out into a separate bug/issue. I've been hesitant to do so though since I don't have a setup to test & verify in isolation everything doesn't work as expected and the problem here isn't some novel debezium interaction.

**Comment by HenryCaiHaiying** [comment]
The VStream tablet_picker currently only specify one cell during constructor time, not multiple cells.  And in tablet_picker.PickForStreaming, I don't see any code favor the current cell vs remote cell.

**Comment by rohit-nayak-ps** [comment]
Fixed via https://github.com/vitessio/vitess/pull/12282
