### ISSUE TITLE
v15 Regression: complex HAVING query - Invalid use of group function

### ISSUE THREAD

**Issue by derekperkins** [vitessio/vitess#11641]
### Overview of the Issue

This was working fine in v14, and works fine against MySQL directly, but started failing after upgrading to v15. This is against an unsharded keyspace.

```sql
select
  loc_id,
  min(created_at) as created_at,
  from_unixtime(min(deadline_at)) as deadline_at,
  count(distinct phrase) total_unique,
  count(*) total_pipelines
from keywordsu.semetrics_grepwords_pipeline
where retrieved_at = 0
  and batch_id = 0
  and api_error = ''
  and provider != 'invalid'
  and location_type not in ('Postal Code', 'Borough', 'Neighborhood', 'National Park', 'City Region')
group by loc_id
having count(*) >= 999
    or min(created_at) + interval 2 hour <= now()
order by total_pipelines desc
limit 100
```

The error is related to the complex `HAVING min(created_at) + interval 2 hour <= now()` clause, as this query runs fine without it.

### Reproduction Steps

Run a query against any table using `HAVING min(created_at) + interval 2 hour <= now()`

### Binary Version

```sh
Docker v15.0.0 for all components
```

### Operating System and Environment details

```sh
GKE 1.21
```

**Comment by derekperkins** [comment]
I just verified that the query runs correctly if `/*vt+ PLANNER=v3 */` is used

**Comment by deepthi** [comment]
@vitessio/query-serving

**Comment by systay** [comment]
@derekperkins Thanks for reporting this!

Could you also share what error you are getting, and which vschema this is against?

**Comment by systay** [comment]
So, the issue here is our rewriting of column names in the `ORDER BY` and `HAVING` clauses. The minimal query that triggers the problem looks like:

```sql
select
  min(created_at) as created_at,
from keywordsu.semetrics_grepwords_pipeline
having min(created_at) <= now()
```

Usually, a column used in ORDER BY and HAVING is pointing to aliases introduced in the `SELECT` expressions. That lead to the query being rewritten to:

```sql
select
  min(created_at) as created_at,
from keywordsu.semetrics_grepwords_pipeline
having min(min(created_at)) <= now()
```

Notice the weird expression in the HAVING clause: `min(min(created_at))`

MySQL has some weird rules around aggregation expressions that Vitess was not mimicking correctly.

Thanks for reporting this, @derekperkins!
