### ISSUE TITLE
Bug Report: v14.0.4 raises unsupported error with a derived table on a reference table

### ISSUE THREAD

**Issue by eseokoh** [vitessio/vitess#11879]
### Overview of the Issue

v14.0.4 regression issue: `unsupported: LEFT JOIN not supported for derived tables`

This worked on v14.0.3.
Related fix: https://github.com/vitessio/vitess/pull/11786

### Reproduction Steps

1. prepare 2 keyspaces: 1 unsharded and 1 sharded. Let's say `ksu` and `kss` respectively. 

2. Deploy vschema to `kss`:
```json
{
  "sharded": true,
  "vindexes": {
    "xxhash": {
      "type": "xxhash"
    }
  },
  "tables": {
    "tsharded": {
      "columnVindexes": [
        {
          "name": "xxhash",
          "columns": [
            "k"
          ]
        }
      ]
    },
    "tunsharded_ref": {
      "type": "reference"
    }
  }
}
```

3. Deploy schema:
```sql
CREATE TABLE `ksu`.`tunsharded` (
  `a` int NOT NULL,
  `b` int NOT NULL,
  `c` int NOT NULL,
  PRIMARY KEY (`a`)
);

CREATE TABLE `kss`.`tunsharded_ref` (
  `a` int NOT NULL,
  `b` int NOT NULL,
  `c` int NOT NULL,
  PRIMARY KEY (`a`)
);

CREATE TABLE `kss`.`tsharded` (
  `k` int NOT NULL,
  `a` int NOT NULL,
  PRIMARY KEY (`k`)
);

insert into `kss`.`tsharded` (`k`, `a`) values (1, 1);
insert into `ksu`.`tunsharded` (`a`, `b`, `c`) values (1, 1, 0);
```

4. Deploy VReplication:
```json 
{
  "workflow": "workflow_ref",
  "source_keyspace": "ksu",
  "target_keyspace": "kss",
  "table_settings": [
    {
      "target_table": "tunsharded_ref",
      "source_expression": "select * from tunsharded"
    }
  ]
}
```

5. Run Query:
```sql
select
        t.k,
        t.a,
        v.b
from tsharded t
left join (
        select
                r.a,
                substring_index(group_concat(r.b, '|' order by r.b asc ), '|', 1) b
        from tunsharded_ref r
        where r.c = 0
        group by r.a
) v
on t.a = v.a
where t.k = 1;
```

6. View error
```
ERROR 1235 (42000) at line 1: unsupported: LEFT JOIN not supported for derived tables
```

Please note that `v14.0.3` worked on this.
Since `tunsharded_ref` is a reference table, I expect we can push the whole query to the target shard of `tsharded`.

7. Remarks

We are considering to upgrade v14.0.3 to v14.0.4 and this blocks.
Our production query is way complicated than this simple reproduction and suffering from the issue of https://github.com/vitessio/vitess/issues/11869. This simple repro does not leave the warning with v14.0.3 but I'd like to report this case as simple as possible. 

### Binary Version

```sh
14.0.4
```

### Operating System and Environment details

```sh
K8s and unrelated.
```

**Comment by kivancbilen** [comment]
Hi, I tried to understand this issue to make my first contribution however I stuck. Here are my findings.

It is failing because derived table has `group by` clause but the column used (in this case "a") in `group by` is not one of the "VIndex" s. When the column is not "VIndex" "IsMergeable" returns false and "requiresSwitchingSides" returns true then 
`LEFT JOIN not supported for derived tables` error is returned.
When I add a "VSchema" with "VIndex" manually then it is working but I know it is not a solution.
`"tunsharded": {
			"columnVindexes": [
			  {
				"name": "xxhash",
				"columns": [
				  "a"
				]
			  }
			]
		  }`
Code is hitting these lines in order
https://github.com/vitessio/vitess/blob/5428112f7838349deaa196a4ee778666df290994/go/vt/vtgate/planbuilder/operators/route_planning.go#L436
https://github.com/vitessio/vitess/blob/5428112f7838349deaa196a4ee778666df290994/go/vt/vtgate/planbuilder/operators/route_planning.go#L415
https://github.com/vitessio/vitess/blob/5428112f7838349deaa196a4ee778666df290994/go/vt/vtgate/planbuilder/operators/subquery_planning.go#L148
Hitting this line because there is `group by` clause
https://github.com/vitessio/vitess/blob/5428112f7838349deaa196a4ee778666df290994/go/vt/vtgate/planbuilder/operators/subquery_planning.go#L168
https://github.com/vitessio/vitess/blob/5428112f7838349deaa196a4ee778666df290994/go/vt/vtgate/planbuilder/operators/subquery_planning.go#L150
Since there are no "VIndex" it is not entering for loop
https://github.com/vitessio/vitess/blob/5428112f7838349deaa196a4ee778666df290994/go/vt/vtgate/planbuilder/operators/route_planning.go#L705

By the way this query is working
`select 
        t.k,
	t.a,
	v.b
from tsharded t
left join (
	select
			r.a,
			r.b
	from tunsharded_ref r
	where r.c = 0
) v
on t.a = v.a
where t.k = 1;`
