### ISSUE TITLE
Bug Report: tabletgateway is making more GetTablet calls to the toposerver in comparison with discoverygateway

### ISSUE THREAD

**Issue by pbibra** [vitessio/vitess#12179]
### Overview of the Issue

We are currently rolling out the `tabletgateway` and noticed that after switching over, our toposerver has been receiving an increased number of `GetTablet` calls. 

We've narrowed it down to this line of code: https://github.com/vitessio/vitess/blob/f33b86219ddc52e17a343fdf842728c0b2eae7cc/go/vt/discovery/topology_watcher.go#L202

We believe this filtering is preventing the watcher from adding tablets ignored by the healthcheck to its cache: https://github.com/slackhq/vitess/blob/ff6807c7c0fb379a69086b413b6eb09a3865e8ef/go/vt/discovery/topology_watcher.go#L177
As a result, we're constantly fetching information for already seen tablets regardless of whether `refreshKnownTablets` is false. 

This is different from the behavior in the `discoverygateway` where this filtering happens when adding the tablet to the healthcheck, not when fetching its info in `loadTablets: https://github.com/vitessio/vitess/blob/bc4a9606e1899a4223b80edfb212f32af81000ac/go/vt/discovery/legacy_topology_watcher.go#L390

### Reproduction Steps

Switching over from discoverygateway to tabletgateway

### Binary Version

```sh
v12
```

### Operating System and Environment details

```sh
N/A
```

**Comment by deepthi** [comment]
I think I understand what is happening. Previously the topology watcher used to cache ALL tablets, not just the ones included in the keyspace/shard filter.
Looks like you will be able to fix this by moving the `isIncluded` check into the next 2 for loops. Check before calling `AddTablet` / `ReplaceTablet` etc. 
I do recommend creating unit tests that fail with the current code and encode the expected behavior before attempting the fix.
