### ISSUE TITLE
Feature Request: read-only policy on vtctld API should have more RO priviledges

### ISSUE THREAD

**Issue by jwangace** [vitessio/vitess#12478]
### Feature Description

Hi Vitess, 

When we start vtctld process, there are 3 security policies, which are deny-all, read-only, and empty.

```
--security_policy string   the name of a registered security policy to use for controlling access to URLs - empty means allow all for anyone (built-in policies: deny-all, read-only)
```

Here is the interesting part, if this flag is not provided, then have full access to all APIs, otherwise, the API put some guard, but only checks if the role is **acl.ADMIN**, for example [this piece of code](https://github.com/vitessio/vitess/blob/main/go/vt/vtctld/api.go#L591-L595) lets the user call vtctl commands over API, which is very useful, but as we run vtctld with read-only flag, we lose this functionality, typically when I want to use it to do some read-only operations, for example, **ListBackups**, this is read-only but also being filtered, I would like to ask you to review the policy and also expose those vtctldclient read-only operations via API.

The current policy for read-only policy is too restrictive (read-only does not expose enough read-only things).

### Use Case(s)
This is a read-only vtctld response to **ListBackups**, which seems shouldn't be filtered on read-only role.
```
$ curl -v -X POST http://localhost:15000/api/vtctl/ -H 'Content-Type: application/json' -d '["ListBackups","mykeyspace/-"]'

< HTTP/1.1 403 Forbidden
```

**Comment by ajm188** [comment]
👋 Hello! Are you running vtadmin? I would say that is the right long(er)-term place to manage these sorts of permissions (as it doesn't go through the vtctld http api at all)

**Comment by jwangace** [comment]
we are running hundreds of clusters without vtadmin unfortunately, but we run vtctld as read-only role, I staged this change in order to intergrade with some automation. Do you think it is a reasonable reason to have this feature on vtctld API?

**Comment by jwangace** [comment]
@ajm188 one reason behind this: I want to display the latest backup file in vtgate /debug/status, adding a new column on table **HealthCheck Tablet Cache**, if vtgate started with --vtctld_addr parameter, when I can call Listbackups through this API.

**Comment by ajm188** [comment]
> we are running hundreds of clusters without vtadmin unfortunately ....
> one reason behind this: I want to display the latest backup file

interesting! it's worth noting that vtadmin has [this exact feature](https://github.com/vitessio/vitess/blob/main/proto/vtadmin.proto#L56-L57) (also available as json-over-http). i don't have any objections _per se_ to this being added, but at the same time i would _strongly_ encourage to move to vtadmin instead; it's where the bulk, if not all, of new cluster management API development is going to be (and also supports multi-cluster deployments as a fundamental design consideration)

**Comment by deepthi** [comment]
Hi @jwangace! We needed to dig into the `vtctld_addr` flag and discuss this before coming back with a response.
There are several existing links on the vttablet `/debug/status` UI and one on the vtgate `/debug/status` UI that link out to the now deleted vtctld web UI. Those links now error out. So we have effectively broken some things on the `/debug/status` pages when we deleted the old UI. We should have also deleted these links at that time.

Given this, we also need to deprecate and delete the `vtctld_addr` flag. It does not make sense to add more functionality that depends on that.
Looking at backups from vtgate is an anti-pattern. VtGate is the query serving component, backups should be viewed via vtctld, so the "new" natural place for them is the VTAdmin UI, since that is the replacement for the old vtctld UI.

This is a long way of saying that we do not want to fix this issue, or accept the PR that you have proposed on the main line of development, which has moved way past the old vtctld UI. Please feel free to do whatever works for you in a fork, but do keep in mind that in v16 the vtctld UI has been completely removed, and the way forward is to start deploying VTAdmin for UI.
