### ISSUE TITLE
Feature Request: If a restore fails, try an earlier backup.

### ISSUE THREAD

**Issue by makmanalp** [vitessio/vitess#13320]
### Feature Description

If a restore fails, retry the restore with an earlier backup file.

### Use Case(s)

We've hit various cases where backups fail because of something inherently wrong with the backup file(s) themselves, one example:

```
F0814 22:49:27.191077      72 action_agent.go:353] RestoreFromBackup failed: NoSuchKey: The specified key does not exist.
	status code: 404, request id: 2EC300308C9C7FC1, host id: CjTxVdno/hy3Qszpuu2JrZcmA6zlJYErKPA0Ev4qjOEbT3crtfJrzxFsZJoLMTn/CbvcDTRCSLo=
cannot open backup file backup.xbstream.gz
Can't restore backup
```

In cases like this, retrying the existing backup doesn't seem to make sense and generally an earlier one will do. Sidenote for this case: it seems like this shouldn't be possible since the MANIFEST file being written is the very last thing that happens and if that's there then it should all be there - we've not been able to figure out exactly how we get into that state, but this patch prevents that from breaking restores, which we use heavily in automation e.g. when creating new pods. I understand that this is not the most satisfying explanation :/ We figured it's still worth sending [our patch](https://github.com/vitessio/vitess/pull/13321) over and you folks can discuss and decide whether it suits.

**Comment by deepthi** [comment]
The argument against automatically trying older backups is that there is no guarantee that the first "good" backup you find is recent enough for the newly restored replica to catch up via binlogs. How are you dealing with this?

**Comment by makmanalp** [comment]
That's a reasonable question - I think our position is that that's always a risk anyway, even the most recent backup might not be recent enough for your binlog retention, and there's already no mechanism in Vitess to check for this. Indeed this already happens to us when if we e.g. start failing to take backups over a long period (tangential: this is a "deal with it monday" for us because we also have alternates like volume snapshots).

On the other hand having this feature means getting paged less due to automation breaking for one off issues we don't necessarily care about. So on balance, personally, this feels like no regression but some decent upside.

It is true that the cost of this is that in the worst case scenario it'll take longer until Vitess reports a failure, but if you're choosing to set `backup_restore_earlier_retries` to be > 1, I think you're quite explicitly accepting that.

**Comment by mattlord** [comment]
cc @shlomi-noach

**Comment by shlomi-noach** [comment]
I'm in favor of the idea, except I think this should be delegated to a human. That is, I don't think Vitess should try an hours long operation automatically. The user should be able to choose the specific backup they want to restore from.

To some extent, this is already supported in the form of `--restore_from_backup_ts` (https://vitess.io/docs/16.0/user-guides/operating-vitess/backup-and-restore/bootstrap-and-restore/). I say "to some extent" because this is a `vttablet` command line flag that applies on `vttablet` startup. It does not work with a `vtctldclient` command.

So, I'm in favor of having a `vtctldclient Restore --from-this-specific-backup-please=....` functionality. The user can script their way to automate restore attempts for previous backups if such command fails.

WDYT?

**Comment by frouioui** [comment]
Hey @makmanalp, we have merged https://github.com/vitessio/vitess/pull/8824 over three years ago. You can run `vtctlclient RestoreFromBackup --backup_timestamp` or `vtctldclient RestoreFromBackup --backup-timestamp`.

cc @shlomi-noach
