### ISSUE TITLE
Feature Request: support `SELECT UNIX_TIMESTAMP(UTC_TIMESTAMP()) AS unix_utc_ts` syntax

### ISSUE THREAD

**Issue by maxenglander** [vitessio/vitess#14340]
### Feature Description

Support this syntax:

```
SELECT UNIX_TIMESTAMP(UTC_TIMESTAMP()) AS unix_utc_ts
```

Which currently returns an error:

```
mysql> SELECT UNIX_TIMESTAMP(UTC_TIMESTAMP()) AS unix_utc_ts;
ERROR 1105 (HY000): the type of this expression cannot be statically computed
```

### Use Case(s)

For legacy applications using this syntax and which cannot be changed.

**Comment by dbussink** [comment]
This one is actually tricky, since we do support evaluating this in the `evalengine`, but the typing is ambiguous. We can disambiguate that, but we need more typing information like the specific underlying type size (a `datetime` behaves different from a `datetime(6)` here for example. See also this:

```
mysql> SELECT UNIX_TIMESTAMP(UTC_TIMESTAMP()) AS unix_utc_ts;
Field   1:  `unix_utc_ts`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       LONGLONG
Collation:  binary (63)
Length:     21
Max_length: 10
Decimals:   0
Flags:      NOT_NULL BINARY NUM 


+-------------+
| unix_utc_ts |
+-------------+
|  1698061205 |
+-------------+
1 row in set (0.00 sec)

mysql> SELECT UNIX_TIMESTAMP(UTC_TIMESTAMP(6)) AS unix_utc_ts;
Field   1:  `unix_utc_ts`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       NEWDECIMAL
Collation:  binary (63)
Length:     19
Max_length: 17
Decimals:   6
Flags:      NOT_NULL BINARY NUM 


+-------------------+
| unix_utc_ts       |
+-------------------+
| 1698061208.568376 |
+-------------------+
1 row in set (0.00 sec)
```

The final type of the `UNIX_TIMESTAMP` function is dependent on the input here, so we need to match that behavior.

**Comment by vmg** [comment]
This will require a moderate refactoring of the planner and evalengine but this was already on the roadmap and so the work is underway :sparkles:
