### ISSUE TITLE
Question: does vitess have a plan to support mgr?

### ISSUE THREAD

**Issue by hustjieke** [vitessio/vitess#14528]
### Question
Hello, everyone, vitess is an outstanding project and I have been following it for a long time.
I'm interested in adpating `MGR` into vitess and I see the `vtgr` had been introduced into vitess in v16 as an experimental properties. 
Refs: https://github.com/vitessio/vitess/issues/13300

I have some questions here, I do many  test on failover cases and found `vtgr` works well. 
Further more, what extent does vtgr adapt to vitess in v16?  Does it works well with other components? I'm now doing adapting work in my personal feature and I found some work has not done yet like  operations on `CLI` & `clustermanager` cmds that interact with `vttablet` RPC interfaces are not suitable directly send to `MGR`.
e.g.   interfaces defined in file: `go/vt/vttablet/tabletmanager/rpc_agent.go`

```
// RPCTM defines the interface implemented by the TM for RPCs.
// It is useful for RPC implementations to test their full stack.
type RPCTM interface {
    // RPC calls
...
    StopReplication(ctx context.Context) error


    StopReplicationMinimum(ctx context.Context, position string, waitTime time.Duration) (string, error)


    StartReplication(ctx context.Context, semiSync bool) error
...
```
For `start or stop replication`, we know it works well in mysql `source-replication` HA mode, but in `MGR`, we know it does through `bootstrap`, in this case, do we still need `StopReplication` or `StartReplication` in `MGR` or we just skip interfaces like this?

**Comment by deepthi** [comment]
Thank you for your kind words.
As stated in #13300, VTGR was not being maintained, and not being used by anyone in production, so it has been removed from the latest version of Vitess (v18).
We (the current maintainer team) are not able to provide any support for VTGR usage in past releases. It is not a good idea to explore this in v16 because there is no support, and no upgrade path.
If and when we decide to revisit MySQL Group Replication support in Vitess, instead of adding yet another binary that you need to run, we would almost certainly fold it into VTOrc, which is the cluster management component in Vitess. If you are interested in exploring a potential design for providing Group Replication support in VTOrc, please feel free to propose it in the form of an RFC. For an example RFC, see #6277.
