### ISSUE TITLE
Adapt Vitess to MySQL deprecation of `WAIT_UNTIL_SQL_THREAD_AFTER_GTIDS`

### ISSUE THREAD

**Issue by shlomi-noach** [vitessio/vitess#14611]
Per MySQL `8.2.0` [release notes](https://dev.mysql.com/doc/relnotes/mysql/8.2/en/news-8-2-0.html):

> Incompatible Change: The WAIT_UNTIL_SQL_THREAD_AFTER_GTIDS() SQL function, deprecated in MySQL 8.0 (see [Changes in MySQL 8.0.18 (2019-10-14, General Availability)](https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-18.html)), has been removed; attempting to invoke it now causes a syntax error. Use [WAIT_FOR_EXECUTED_GTID_SET()](https://dev.mysql.com/doc/refman/8.2/en/gtid-functions.html#function_wait-for-executed-gtid-set) instead. (WL #13180)

Both [5.7 docs](https://dev.mysql.com/doc/refman/5.7/en/gtid-functions.html#function_wait-until-sql-thread-after-gtids) and [8.0 docs](https://dev.mysql.com/doc/refman/8.0/en/gtid-functions.html#function_wait-for-executed-gtid-set) suggest that `WAIT_FOR_EXECUTED_GTID_SET` should be used, instead. In vitess, we never actually use the channel parameter, so for Vitess the usage is identical for both.

**Comment by mattlord** [comment]
Re-opening this as we had to [revert the original changes](https://github.com/vitessio/vitess/pull/14742) because the results from the two functions are inverted and it [led to errant PRSs](https://github.com/vitessio/vitess/issues/14738).

We should still do this work ASAP, but some additional slight refactoring should also be done so that e.g. we handle the results as 0 (success) and non-zero (failure) values like unix exit code values -- this way the results will be compatible across versions (and MariaDB).
