### ISSUE TITLE
Bug Report: schemadiff incorrectly reports diff in indexes

### ISSUE THREAD

**Issue by GrahamCampbell** [vitessio/vitess#15463]
### Overview of the Issue

The schemadiff system is incorrectly reporting a semantic difference in two tables that are identical up to renaming of indexes.

### Reproduction Steps

a.sql
```sql
CREATE TABLE `example` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `foo_id` int unsigned NOT NULL,
  `bar_id` int unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_example_foo_bar` (`foo_id`,`bar_id`)
) ENGINE=InnoDB;

```

b.sql
```sql
CREATE TABLE `example` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `foo_id` int unsigned NOT NULL,
  `bar_id` int unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_foo_bar` (`foo_id`,`bar_id`)
) ENGINE=InnoDB;
```

command
```bash
./schemadiff diff --source a.sql --target b.sql
```

actual output
```sql
ALTER TABLE `example` DROP KEY `idx_example_foo_bar`, ADD KEY `idx_foo_bar` (`foo_id`, `bar_id`);
```

expected output
```sql

```

### Binary Version

```sh
schemadiff v1.1
```

### Operating System and Environment details

```sh
MacOS 14.4 (23E214), Apple M3 Max (arm64).
```

### Log Fragments

Related: https://github.com/planetscale/schemadiff/issues/20.

**Comment by shlomi-noach** [comment]
Thank you for looking into `schemadiff`! `schemadiff` respects key name changes.

Key names are meaningful: for example you might be running queries like `SELECT * FROM t FORCE INDEX (index_name) ...`.

`schemadiff` does ignore key ordering (ie which key comes after which other key in the schema definition). `schemadiff` also ignores `CONSTRAINT` names, but that's imposed on `schemadiff` due to the nature of constraint names being unique across the schema, as opposed of across the table namespace.

With that, I'll be closing this issue as "not a bug". I'll leave it open for a couple hours to give way to some more discussion.

**Comment by GrahamCampbell** [comment]
Odd. It was not reporting changes in other places where the index names were different.

**Comment by GrahamCampbell** [comment]
Hmmm, maybe I'm mistaken there. Thanks for your help.
