### ISSUE TITLE
Vitess usage of Equinix resources

### ISSUE THREAD

**Issue by jeefy** [vitessio/vitess#15816]
Hello! Friendly neighborhood CNCF staffer here. 

Per the [maintainer newsletter sent out in February](https://contribute.cncf.io/resources/newsletters/2024-02-21-projectnewsletter/#-resource-provider-mega-thread), we're aiming to reduce needless machines running in Equinix and use the donated resources responsibly. Since Equinix is bare metal, even machines that are powered off are still being "used" so, where possible we want to ensure you're only spinning machines up when-needed and tearing them down when not.

We see you have a `m2.xlarge.x86` that was created at the beginning of February and seems idle based on network traffic. Can you please remove it and only spin it up when actively needed?

Also, we see you have a `c3.small.x86` that is a GitHub Action Runner. Could you please instead either use GitHub's native GHA runners, or one of the [runners set up within the CNCF Infra](https://contribute.cncf.io/resources/newsletters/2024-02-21-projectnewsletter/#github-action-runners)? Happy to connect with someone if needed.

Thanks!

cc @vielmetti

**Comment by frouioui** [comment]
Hello @jeefy!

I have removed the `m2.xlarge.x86` since we were no longer using it.

Regarding the `c3.small.x86` server, it is still used frequently to perform all kind of builds and tests. However, the naming is wrong, it used to be called github action runner, but we don't actually use it as such. I renamed the server for more clarity. If us using this server is problematic for Equinix and CNCF we could choose another server size or AZ that is less demanded by other users.

We have four more servers under a different Equinix project called `Vitess-perf-testing`, but all of those servers are used extensively every day.

Thank you for keeping track of this! 🙇🏻
