### ISSUE TITLE
LFX community building

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#15895]
### Scope
- Contributor Community
  - [ ] Review available contributor ladder and reward schemes and create a proposal
  - [ ] Implement approved contributor ladder and rewards
- User Community
  - [ ] Develop interview questionnaire
  - [ ] Identify participants
  - [ ] Conduct user interviews to gather data from community users
  - [ ] Analyze collected data
  - [ ] Publish a blog post with findings
- Marketing
  - [ ] Research possible channels and provide recommendations
  - [ ] Organize and facilitate implementation of agreed upon plans
- Website docs
  - [ ] https://github.com/vitessio/website/issues/1738 

### Mentors
- @deepthi (Primary)
- @frouioui (Backup)

### Contact
You can join the #lfx channel in our [slack community](https://join.slack.com/t/vitess/shared_invite/zt-2he4t8glg-hyLiiW~f_0YM2YD9oYYuuA).

**Comment by h4l0gen** [comment]
Hello @deepthi, I find your proposal for LFX Term 2 to grow the Vitess community quite intriguing. What are the first steps you would recommend I take to be a mentee on this project? From the listed skills, here's what I have:

-     Prior exposure in an open-source community.
-     I also possess skills in website development.

**Comment by Ayush9026** [comment]
Hi @deepthi mam,

I'm interested in the CNCF - Vitess community building program for Term 2. Excited about evaluating contributor schemes, enhancing docs, and exploring marketing for Vitess.
I have extensive experience contributing to open-source projects, particularly in the Kubernetes ecosystem and other CNCF initiatives.

**Comment by deepthi** [comment]
@h4l0gen @Ayush9026 The best thing I can recommend for you is to spend a little time exploring the Vitess website and the community slack. We will be evaluating applications through the LFX portal, so please make sure to highlight your prior experience in your application.

**Comment by Ayush9026** [comment]
Thank you @deepthi mam for guiding 🙏🙏.

**Comment by kirtanchandak** [comment]
Hey @deepthi, 

I am Kirtan a Full Stack Developer from India. I've been involved in **Vitess: arewefastyet** project since the last LFX'23 term and also have some contributions in there. 

Would love to take up the task for community building for Vitess. I have been involved in the tech community since 2021 by participating in hackathon, attending conferences and contributing through code, blogs and volunteering. 

Also, I have decent experience in website development with React, Next.js, and Express.js for backend. 

Would love to work with Vitess this summer and make a cherished and interactive community. 

Thank You!

**Comment by deepthi** [comment]
Mentorship is complete.
