### ISSUE TITLE
Feature Request: SQL syntax for schema tracking

### ISSUE THREAD

**Issue by aparajon** [vitessio/vitess#15921]
### Feature Description

Add SQL syntax that can detect the status of **schema tracking** and/or trigger it to catch up. 

One possible way that this can look like:

```
>  show schema_tracking;
+--------------+
| Status       |
+--------------+
| IN_PROGRESS  |
+--------------+

> await schema_tracking;
+--------------+
| Status       |
+--------------+
| COMPLETE     |
+--------------+
```

### Use Case(s)

A client app might want to run these commands against the `vtgate` before issuing further app specific SQL commands. Specifically, this would be useful for tests that run against `vttestserver`, as there can be a case where all `.sql` migrations appear to be applied but schema tracking has not yet caught up and the error `VT09015: schema tracking required` gets emitted. 

The context / motivation for this feature request originates from this [Slack thread](https://vitess.slack.com/archives/C0PQY0PTK/p1715016394876369). It seems like schema tracking is actually enabled based on `schema_change_signal` and `queryserver-config-schema-change-signal`  having a default value of `true` in [vtcombo](https://github.com/vitessio/vitess/blob/f27d287e0873d139ad2f71588068256e28a16f6a/go/flags/endtoend/vtcombo.txt#L317). And FYI, it seems like I only hit this error in versions of Vitess >= 18, as I haven't yet hit this issue after downgrading tests to run against v17. I'm also open to exploring other ideas or suggestions on how to wait for schema tracking to complete.

**Comment by harshit-gangal** [comment]
It interests me that the issue does not exist on v17 and only happens for v18+.
Can you share the Vschema and the query on which you see the error?

**Comment by aparajon** [comment]
Shared privately

**Comment by harshit-gangal** [comment]
We have discussed this issue. It seems that this problem is mainly related to testing. Before we begin testing, we need to ensure that the schema information is up to date on the VTGate.

The Vitess testing code utilizes the VTGate's `debug/vschema` URL to retrieve the vschema and verify whether the schema is updated with the necessary information to conduct the test.

I'm referring to the code utilized in our testing, which can also be used by your testing infrastructure to address the current issue.

https://github.com/vitessio/vitess/blob/main/go/test/endtoend/utils/utils.go#L247

Let us know if this helps.

**Comment by aparajon** [comment]
Tanks looking into this @harshit-gangal. Interestingly it seems like this issue has no longer been happening in newer versions of Vitess and I have not yet encountered it again. But should the issue arise, I think the logic you shared should suffice. I'll go ahead and close this issue, thanks again!
