### ISSUE TITLE
Why do I use Spring JDBC to directly connect to MySQL to update the same records, which affects 1 rows, but using Spring JDBC to connect to Vitess affects 0 rows

### ISSUE THREAD

**Issue by tss3023coding** [vitessio/vitess#17132]
### Question

Why do I use Spring JDBC to directly connect to MySQL to update the same records, which affects 1 rows, but using Spring JDBC to connect to Vitess affects 0 rows.
![image](https://github.com/user-attachments/assets/ddd3db69-0a05-4b4c-92e8-0244cddecb20)

**Comment by mattlord** [comment]
Hi @tss3023coding,

This is not a question that can be answered — it's something that will require a good amount of back and forth to get much more context — so I'm going to close this as the project issues aren't the proper venue for this kind of help. Please raise this issue in [the Vitess Slack](https://vitess.io/community/) so that the community can try and get you the help you need.

Best Regards
