### ISSUE TITLE
Incompatibility Documentation

### ISSUE THREAD

**Issue by derekperkins** [vitessio/vitess#2274]
Searching around, I haven't found any good documentation on what isn't supported by Vitess. Scanning the issues here and scattered throughout the docs, I've found that the following MySQL limitations:
 - UPDATE with JOIN
 - multi row inserts
 - multi row updates
 - JSON fields
 - 100k row limit for schema changes
 - no RBR

It would be nice to add a page to the website where these were listed out in one place. It would make the choice whether or not to migrate to Vitess easier if any of those were dealbreakers.

**Comment by sougou** [comment]
This is a good idea. I'll discuss it with the team. As for the features you mentioned, most of them are either being worked, or are on our radar:
* UPDATE with JOIN is on our radar. Until then, the work-around is to rewrite those as `SELECT pk... FOR UPDATE` and follow it with `UPDATE... where pk`. That is also how we plan to make it work when we implement it.
* multi row inserts are being worked on by Flipkart.
* multi row updates will follow soon after multi row inserts.
* JSON fields: It looks like this is a show-stopper. I'll try to prioritize this. So, expect something on this very soon.
* 100k row limit: I believe this is configurable. Let us know if you can't find the flag.
* no RBR: This is also on our radar. Note that vitess's SBR is almost as efficient as RBR because it rewrites all your DMLs to be pk-based. So, if performance is the only reason you're on RBR, we'd recommend you to switch to SBR when you migrate. You won't lose much. If there are other reasons, then you'd have to wait till we make Vitess work with RBR.

**Comment by morgo** [comment]
This will be added in https://github.com/vitessio/website/pull/325

Because there is already a documentation repo issue about this ( https://github.com/vitessio/website/issues/222 ), I am going to close this one now.
