### ISSUE TITLE
Thoughts on documentation for newcomers to Vitess

### ISSUE THREAD

**Issue by sjmudd** [vitessio/vitess#2887]
Vitess does have quite a lot of documentation and that's really good. There's clearly been a lot of work put into explaining how the system works etc. However, for someone who is looking to migrate to Vitess, or at least consider this a number of questions arise, some of which perhaps are not answered with the focus of a newcomer who already has an existing setup and is hoping Vitess will make his life easier.  Answering these questions will probably allow him to get up to speed faster.

Some things which I have asked (and I'm still learning how it all works) are:
* I have an existing replication chain and I want to put Vitess on top (but maybe only talking to a spare replica/slave). What's the minimum configuration needed to do this?  My answer so far seems to be to setup vttablet , vtgate and configure zookeeper (in my case) accordingly.  Terminology can be a bit confusing so talk in terms of the terms used by the newbie not in vitess terms here.
* I have an existing sharded replication chain and want to put Vitess on top of it (again just talking to a spare replica). What's needed to do that?  This seems to additionally require the configuration  of the vschame and vindexes which will obviously depend on the specific setup.  It looks like you need to configure this for each table in the existing database, and the mapping may depend on various factors. Clearly range based sharding works easily ,  and using a hash basically splits the key value into a hash which is then "range bound" into different shards. This wasn't apparent to me initially. Again here examples of the process of configuring each shard would be good

Other questions which arise and I've not resolved are:
* Can I use vitess to auto-reshard my existing setup just by pointing it at some slaves/replicas? If so how and what other conditions need to be fulfilled?
* If I have my own backup /restore mechanism how can I integrate it so Vitess can use it?  Pointers to what's done already , to interfaces that need to be configured in code and to the functional aspects that need to be considered would be useful.
* The resharding seems to require doing backups and restores and then applying filters. If I have an existing "unmanaged" cluster can I reshard into a managed one?
* what does managed actually mean? it seems that this requires a very specific set of interfaces to control vitess and each of the components within it. Are they clearly defined?  As it might be interesting if this were pluggable to replace it with already existing infrastructure if that proved more convenient. Again this may not make sense but if someone has already invested quite a bit of time into existing infrastructure migration may be hard. If Vitess could reach out with appropriate hooks to do all these tasks then it would make integration into more systems easier.
* Monitoring - we already monitor our servers so that seems ok. What needs monitoring in terms of the Vitess processes and activities that it is doing?
* Plugins - vitess is already "pluggable" in many parts of the way it works. These plugins are not very clearly defined in the sense there is no doc that says: if you write a backup plugin this is where you need to write it and these are the interfaces you need to comply to.  This is true of the sharding plugins too.  This probably does not require much to be written but it then becomes clear how you may be able to integrate your own system with Vitess. 

These are just a list of a few thoughts. hopefully they are useful.

**Comment by acharis** [comment]
Agreed!

I'll add that, while I have no source for data here, my hunch is that Vitess will have the most traction from, and therefore need for documentation for, people who are migrating existing systems onto Vitess. That group might be best helped by us pioneer migrators, rather than the YouTubers who were responsible for growing Vitess along with the rest of YouTube. We'll bring to the docs a breadth of experience that might be more widely useful.

**Comment by timglabisch** [comment]
i tryed to setup vitess on a bunch of blank cloud servers following https://vitess.io/docs/tutorials/local/ .
I am a newcomer to vitess but i like the idea and want to play with it. The instructions are not complete and confusing for newcomers. 

it would be a great if the first steps with vitess would be more beginner friendly. Pre-build binaries and a copy&paste solution for an easy production ready cluster would be great.

**Comment by morgo** [comment]
Some specific responses inline:

> I have an existing replication chain and I want to put Vitess on top (but maybe only talking to a spare replica/slave). What's the minimum configuration needed to do this? My answer so far seems to be to setup vttablet , vtgate and configure zookeeper (in my case) accordingly. Terminology can be a bit confusing so talk in terms of the terms used by the newbie not in vitess terms here.

* I have tried to make the concepts easy by adding a Top-level "Concepts": https://vitess.io/docs/concepts/ -- related: the documentation structure is now using DITA, which is more common to technical docs.

* There is a page which refers to Production Planning, but it is not clear what the minimum requirements are: https://vitess.io/docs/user-guides/production-planning/ -- we should make it clearer minimum vs. recommended. I will fork this to https://github.com/vitessio/website/issues/335

* Currently no migration guide from existing MySQL, but one is planned: https://github.com/vitessio/website/issues/263

> I have an existing sharded replication chain and want to put Vitess on top of it (again just talking to a spare replica). What's needed to do that? This seems to additionally require the configuration of the vschame and vindexes which will obviously depend on the specific setup. It looks like you need to configure this for each table in the existing database, and the mapping may depend on various factors. Clearly range based sharding works easily , and using a hash basically splits the key value into a hash which is then "range bound" into different shards. This wasn't apparent to me initially. Again here examples of the process of configuring each shard would be good

I think this is a little harder to document moving a sharded system to Vitess (as a guide), since the users scheme may differ. But I think we can document vschema and vindexes better as reference concepts. Improvements are being tracked at https://github.com/vitessio/website/issues/331

> Other questions which arise and I've not resolved are:
> Can I use vitess to auto-reshard my existing setup just by pointing it at some slaves/replicas? If so how and what other conditions need to be fulfilled?

No. Or at least not currently, you will need to design a vschema to shard.

> If I have my own backup /restore mechanism how can I integrate it so Vitess can use it? Pointers to what's done already , to interfaces that need to be configured in code and to the functional aspects that need to be considered would be useful.

I would like to document the included methods better first. The user guide page is: https://vitess.io/docs/user-guides/backup-and-restore/ -- it is a bit too much of a reference page, and not a guide at this point. I have plans to improve it.

> The resharding seems to require doing backups and restores and then applying filters. If I have an existing "unmanaged" cluster can I reshard into a managed one?

A guide on unmanaged to managed is planned https://github.com/vitessio/website/issues/263

> what does managed actually mean? it seems that this requires a very specific set of interfaces to control vitess and each of the components within it. Are they clearly defined? As it might be interesting if this were pluggable to replace it with already existing infrastructure if that proved more convenient. Again this may not make sense but if someone has already invested quite a bit of time into existing infrastructure migration may be hard. If Vitess could reach out with appropriate hooks to do all these tasks then it would make integration into more systems easier.

These are documented here: https://vitess.io/docs/user-guides/vttablet-modes/
I think that the guide of moving from unmanaged to managed will be very basic to start with, but we can consider other cases from there.

> Monitoring - we already monitor our servers so that seems ok. What needs monitoring in terms of the Vitess processes and activities that it is doing?

Thanks! I have added monitoring to the list of guides required: https://github.com/vitessio/website/issues/263

> Plugins - vitess is already "pluggable" in many parts of the way it works. These plugins are not very clearly defined in the sense there is no doc that says: if you write a backup plugin this is where you need to write it and these are the interfaces you need to comply to. This is true of the sharding plugins too. This probably does not require much to be written but it then becomes clear how you may be able to integrate your own system with Vitess.

I would like to work on out of box cases before documenting custom plugins. The included plugins has improved recently with xtrabackup support, so if something is missing lets capture the requirement first.

**Comment by morgo** [comment]
Thank you again for the feedback. I have broken some of the action points up into sub-tasks, so I am going to close this issue for now. Please feel free to re-open it if you have followup questions.
