### ISSUE TITLE
An interrupted ./bootstrap.sh may not check or pull down the right zookeeper files.

### ISSUE THREAD

**Issue by sjmudd** [vitessio/vitess#2899]
I interrupted a bootstrap.sh run then ran it again:

```
[myuser@myhost ~/src/youtube-vitess/src/github.com/youtube/vitess]$ ./bootstrap.sh
Updating git submodules...
--2017-05-30 12:27:26--  http://apache.org/dist/zookeeper/zookeeper-3.4.6/zookeeper-3.4.6.tar.gz
Length: 17699306 (17M) [application/x-gzip]
Saving to: ‘zookeeper-3.4.6.tar.gz.2’

zookeeper-3.4.6.tar.gz.2       100%[===================================================>]  16.88M  1.73MB/s    in 13s

2017-05-30 12:27:39 (1.33 MB/s) - ‘zookeeper-3.4.6.tar.gz.2’ saved [17699306/17699306]
```

Note that the file being downloaded is not the "intended" `zookeeper-3.4.6.tar.gz`. I would suggest here that if you know the checksum you can verify the file prior to downloading it again, or if not just overwrite the existing file.  This probably just requires invoking wget differently.

Seen against commit 61b52b0c6b10 from May 27th.

**Comment by morgo** [comment]
I think long term Vitess should get out of the business of bundling third party binaries. It creates an issue where if there is a lot of surface area for re-packaging on security vulnerabilities etc.  Having said that, ZooKeeper is a bit of a tricky one since it is not always reliably in distros.

In https://github.com/vitessio/website/pull/372 I have changed the bootstrap so that users are encouraged to use 'make tools' instead. This is also now only required for testing (not building), so I am inclined to say that we won't fix this.. and will handle it as a support issue instead.

Thank you for reporting this issue, and please feel free to re-open if you feel otherwise.
