### ISSUE TITLE
Cannot cache field info

### ISSUE THREAD

**Issue by alouane** [vitessio/vitess#2966]
Hi
Can someone point me out what this error means

![image](https://user-images.githubusercontent.com/3225153/27513027-926b4494-5946-11e7-837b-b575471aa8c2.png)

Is there something wrong with these queries?

Thanks

**Comment by sougou** [comment]
Alouane:
This is an optimization warning. It basically says that it can't cache the field info for the query (col name, type, etc). So, it will rebuild that info for every query.

The only time it should be unable to perform this caching is if you're using bind variables in your select expression (like `select :a...`). If so, the field info will change depending on the value you passed.

However, it looks like the analyzer has a bug. It's triggering this even if your `group by` expression has bind vars. The fix is trivial. I'll keep this bug open for it.

Until then, the queries should still execute fine. They may just be marginally more expensive than usual.

**Comment by aquarapid** [comment]
https://github.com/vitessio/vitess/pull/3538 removed this error message

**Comment by ajm188** [comment]
closing due to #3538
