### ISSUE TITLE
Feature: reconfigure components at run time without the need to restart them

### ISSUE THREAD

**Issue by guidoiaquinti** [vitessio/vitess#2983]
This feature request is probably not very useful for container based deployments but I can see it pretty valuable for all the other setup.

**Comment by sougou** [comment]
This was a conscious decision we made. We even deleted code that used to allow state changes.
The main reason was because vt components are lightweight and can be restarted very quickly.

Additionally, vt servers have the zero-downtime ability where if you start a process on the same port as the old one, the new process gracefully takes over the traffic from the old process and then kills it.
It's something we haven't tested since we added support for grpc. But if there are problems, the fix should be easy. This feature is specifically for a non-container environment.

**Comment by giaquinti** [comment]
Thanks @sougou. I opened this issue as I wasn't aware of the upgrade ability that you described (I didn't find it in the docs). I can take care to add it in the docs if you agree

**Comment by sougou** [comment]
Sure. For reference, the code is here: https://github.com/youtube/vitess/blob/master/go/proc/proc.go.
One open question is about grpc listening on a different port. There could be some issues related to that. We may have to sequence the listeners such that grpc isn't started until the port is obtained by the new process.
