### ISSUE TITLE
float field may lead to binlog player append data inconsistent

### ISSUE THREAD

**Issue by xhh1989** [vitessio/vitess#3045]
during a binlog player running, if binlog_format=row and a table has float filed, update or delete operation may lead to data inconsistent,  for example  table t has float filed f;
create table t(id int, f float);
a delete operation on source shard: delete from t where id = 1;
binlog_format is row,then  a sql genetate by binlog streamer like this:  delete from t where id = 1 and f=3.14;
the float filed f=3.14 in destination shard can't match any row. We can't use  compare equal on float value.   the same as update operation.

binlog_format=statement is ok.

**Comment by alainjobart** [comment]
Looking into this, this is a real issue. I don't have any idea on how to fix it. Any idea, anyone?

(well the long term plan we may have is as follows: instead of connecting to MySQL and converting RBR events into SQL and sending them, we configure MySQL to connect to the local vttablet as a slave and send the events as is. That way we don't have to print the fields as SQL, they can just stay binary. That's a big change).

**Comment by sougou** [comment]
I discussed this with @alainjobart. For the short term, we're thinking of changing the player to update by primary key. Of course, this will make it vulnerable to on-the-fly schema changes, but it's better than the current behavior.

**Comment by alainjobart** [comment]
Another workaround is to use the:
binlog_row_image=minimal
MySQL option. When doing so, MySQL will only use the primary key to identify rows (or a unique index). I'm assuming your float columns are not part of the primary key? Then Vitess will only use what MySQL gives to identify the columns, and not the float columns.

See:
https://dev.mysql.com/doc/refman/5.7/en/replication-options-binary-log.html#sysvar_binlog_row_image

**Comment by xhh1989** [comment]
Now, I just skip the float and double field, and  other fileds reserved.  
 Why we can not  use  '>' and '<' compare float field，for example f is 3.14, rewrite where condition : where f >3.139 and f < 3.141 .

**Comment by bbeaudreault** [comment]
In that case 3.14 and 3.1401 would be considered equal

**Comment by xhh1989** [comment]
yes, but there still primary key  and other filed in where condition， just a  compromise.

**Comment by sougou** [comment]
I think a primary-key based update will cover all the common use cases, maybe even all. This is because we don't expect you to apply schema changes during a resharding process. I believe the current process requires you to independently deploy schema changes on source and target tablets, and then resume filtered replication.
