### ISSUE TITLE
Expose variable for systems running on Vitess 

### ISSUE THREAD

**Issue by guidoiaquinti** [vitessio/vitess#3112]
Right now there isn't an easy way to understand from a MySQL interface if the the server is running on Vitess. 

My proposal is to add a new `@@vitess` variable or extend the already present `@@version_comment` (appending to that value).

Example:
```
mysql> SELECT @@version_comment;
+--------------------------------------------------------+
| @@version_comment                                      |
+--------------------------------------------------------+
| Percona Server (GPL), Release '16', Revision 'd7301f8' |
+--------------------------------------------------------+
1 row in set (0.00 sec)
```

**Comment by sougou** [comment]
We could return a custom response to the version comment. Some possible concerns:
* Software that doesn't tolerate variations in such strings may fail.
* Some software may still want to know the correct mysql version underneath vitess. Of course, this is a future concern if/when we decide to pass through such a request.
* We should also start returning the vitess release number and the github commit hash, which could come in handy.

A possible trade-off: If no keyspace is specified, return `Vitess, Release '3.0', Revision 'xyz'`. If a keyspace is specified, then we pass it through as DBA statement to MySQL.

**Comment by sjmudd** [comment]
Some thoughts more related to `@@version` but also applicable to `@@version_comment`:
* I've seen some of my software even get confused by custom builds of MySQL so that's a real concern (though often this software should be made to be more tolerant of what it expects). Fixing upstream software to be more tolerant is worth doing.
* previous experience with the MaxScale binlog router (that didn't talk to multiple backends, just one) made it collect the upstream server's `version` and `version_comment` and report that.  If all backend db `version`/`version_comment` are the same that would work but I would expect in practice this would not be the case. This lead to the option to lie to the client and provide a hard-coded value.  While not that flexible that often might be good enough.
* mysql clients do care about the version of MySQL they are talking to so at some point it would be good for Vitess to be helpful. It's more important if using the MySQL protocol as the client may really think it's talking to Vitess.

So my thought would be to allow for one of several options:
* choose `@@version` / `@@version_comment` if all backends use the same value
* choose a random shard's `version` / `version_comment`. That may lead to varying values seen by the client but it relfects reality and what is behind vtgate.
* provide an option for vtgate to tell the client it's a specific version or version_comment (just tell a lie).
* perhaps also consider showing the *highest* or *lowest* values of all the servers serving the keyspace
* provide _additional_ Vitess-specific session variables. This is what MaxScale did, so something like `@@vitess_version` or `@@vitess_version_comment` . This is good for monitoring systems which may not be quite sure what they're actually talking to, and so are able to figure it out with the appropriate query (and then adjust their behaviour accordingly) and in practice most normal clients won't notice or be affected.

Orchestrator is an example where this had to be handled as orchestrator needed to do special things with a binlog server compared to a normal MySQL server and these extra settings allowed it to figure out correctly the type of server it was talking to.

**Comment by morgo** [comment]
This will help with support requests as well since we plan to significantly improve SQL support in coming releases.
