### ISSUE TITLE
vtworker should only show tail of log on status page

### ISSUE THREAD

**Issue by tirsen** [vitessio/vitess#3545]
If you have a long running task with lots of log output the vtworker the status page takes a really long time to load. We should limit the amount of log output we show (showing only the most recent N rows).

**Comment by mattlord** [comment]
I'm going to close this for now as with 6.0+ we have the [`vreplication`](https://vitess.io/docs/reference/vreplication/vreplication/) workflows [that should be used instead of the legacy sharding work with `vtworker`](https://vitess.io/docs/user-guides/historical/). If you feel that you still have a valid use case for the legacy tooling today please let us know. Thanks!
