### ISSUE TITLE
Support START TRANSACTION options in Vitess

### ISSUE THREAD

**Issue by dweitzman** [vitessio/vitess#3637]
vtgate rejects transactions on REPLICA and READONLY (https://github.com/youtube/vitess/blob/5ab58f3f0d3839f635dea017044490ffc1ca71cf/go/vt/vtgate/executor.go#L136)

Read-only transactions can be useful in mysql for controlling read isolation and doing consistent reads.

"START TRANSACTION READ ONLY" and "START TRANSACTION WITH CONSISTENT READ" are valid mysql statements that seem fine to support on replicas. I have no idea how it manifests in the binary protocol if you're using the mysql JDBC connector and do connection.setReadOnly(true), possibly change a transaction isolation setting, and then call setAutoCommit(false)

In principle it seems like there's no reason vitess would need to forbid that.

**Comment by sougou** [comment]
I believe this is not a requirement anymore, at least not for the short term.

**Comment by aquarapid** [comment]
Reopening;  since Vitess still does not support any of the `START TRANSACTION` options (`READ ONLY`, `READ WRITE` or `WITH CONSISTENT SNAPSHOT`) as a syntax issue. 

I think the main use-case here is for application compatibility.  Note that at the time this issue was originally logged, we did not support transactions against replicas, but we do now.  However, this issue of syntax applies to operations against master instances as well.
