### ISSUE TITLE
Enforce Vanity URLs

### ISSUE THREAD

**Issue by derekperkins** [vitessio/vitess#3736]
Even though we added custom import paths, we aren't currently enforcing them, which could potentially cause import conflicts if you accidentally use a github.com import path. For example, would need to change `package vtgate` to 

```
package vtgate // import "vitess.io/vitess/go/vt/vtgate"
```

OpenCensus just dealt with this recently.
https://github.com/census-instrumentation/opencensus-go/pull/389/files

This isn't terribly important, but I came across it and figured it was worth noting.

**Comment by sougou** [comment]
+1
golang also seems to be doing the same thing: https://github.com/golang/net/blob/master/html/doc.go#L96

**Comment by J0** [comment]
Hey @deepthi can I take this issue?

**Comment by deepthi** [comment]
@J0 sure!

**Comment by J0** [comment]
After discussion with @enisoc, we realized that this issue might be obsolete since we switched to go modules. As per the [Go mod](https://github.com/golang/go/wiki/Modules) document, Go mod enforces a module path for each module and the go tool enforces consistency between that declared module path and the import paths used by any consumer.  As such, we might not need vanity urls to enforce paths.
