### ISSUE TITLE
Docment vitess mysql procotol help / show help

### ISSUE THREAD

**Issue by linuxgood1230** [vitessio/vitess#3889]
- mysql proctol support which show command need docment
- Now I saw test case find many show command , no documents
```
 grep  "show " vitess/go/vt/vtgate/executor_test.go|egrep Errorf|awk -F: '{print $1}'|sed 's/t.Errorf("//g'|sort |uniq
```
               - show databases
               - show vindexes
               - show vindexes on TestExecutor.test
               - show vindexes on TestExecutor.user
               - show vindexes on user
               - show vindexes on user2
               - show vitess_shards
               - show vitess_tablets
               - show vschema_tables

**Comment by morgo** [comment]
The MySQL protocol support is now documented. Some of it in this upcoming PR: https://github.com/vitessio/website/pull/333

We should add a new section called "Extensions to MySQL syntax". I have created https://github.com/vitessio/website/issues/336 to track.

(I am going to close this issue now, since docs issues are tracked int he vitessio/website repo.)
