### ISSUE TITLE
Errors in Filtered Replication are not consistently reported on the vttab status page

### ISSUE THREAD

**Issue by eeSeeGee** [vitessio/vitess#4147]
#### Overview of the Issue

While a pending split was in filtered replication a binlog replay error occurred which prevented further syncing. Looking at the status page for vttablet SecondsBehindMaster was 0 and there was no error in the Last Error field. In actuallity filtered replication was ~30 min behind and was not progressing. Refreshing the page a few times did eventually show the error, however SecondsBehindMaster was still 0.

Any blocking error should reliably show up here. It would also be nice if the UI showed something other than "0" when there's a problem.

**Comment by sougou** [comment]
The reported error gets cleared when vttablet attempts to restart replication, which is why it gets intermittently shown. Leaving the error as is can cause confusion: replication might now be going well, but the lingering error can make you think that replication is broken.

I'm thinking we could display it as a log of the last 3-5 events. This will make it more readable.

As for the "0" lag problem, it's something that we need to find a deeper solution for.
