### ISSUE TITLE
Slow writes after PlannedReparent

### ISSUE THREAD

**Issue by rafael** [vitessio/vitess#4161]
### Description

We have been debugging for a very **long** time an issue where after we PlannedReparent a shard, we get a spike of errors with the following symptoms:

1.    New master is accepting writes, but it's taking a long time to commit this transactions.
1.    Transaction pool get's exhausted and errors are propagated to the app. 
1.    After a few seconds, new master **warms** up and starts accepting writes. 

For context, a little bit about environment. We have some shards that have high write voulme. We use RBR with semi-sync in MySQL. Due to RBR and how we rotate our binlog files, they can grow to considerable large amounts (hundreds of MB) in a relative short period of time.

We've been having a theory where we think that the newly promoted master is not fully ready to receive semi-sync acks. @sougou had an explanation for this in: https://vitess.slack.com/archives/D6L0T2UAV/p1535427769000200. The problem could be because the master has to scan the binlogs to find the requested GTID.

Today @demmer had a really good idea and proposed that before doing a **PlannedReparent** we should **`FLUSH BINARY LOGS`** in the **replica** (soon to be master) so MySQL closes current binlog file and creates a new one. With this change, if there a writes that happen after the flush (which will always be the case in Vitess, due to PlannedReparent inserting rows in `_vt.reparent_journal`), scanning that file should be fast because it will be small. 

### Tests 

I did the following test in our dev environment with some promising results: 

1.  Generate tons of writes. 
1.  Wait for the binlog to grow (300/400 MB)
1.  Perform a `PlannedReparent`.
1.  Time how long it takes to perform this operation.
1.  Repeat the test, but run `FLUSH BINARY BINLOGS` in the target replica before reparenting.

Results:
1. Reparenting without flushing binlogs: ***20 to 30 seconds***. This is consistent with what we see in prod.
1. Reparenting with flushing binlogs: ***less than second***

### Proposal

We should enhance *PlannedReparent* to  `FLUSH BINARY BINLOGS` before promoting the target replica to master.

**Comment by sougou** [comment]
@shlomi-noach any thoughts on this?

**Comment by shlomi-noach** [comment]
Yeah, that makes sense to me. It is one of the unfortunate designs of GTID where you need to scan the entire binlog to make the first connection (with Pseudo-GTID you get markers throughout the binlog file and quick jump into the end of file).

I have also observed cases (recurring, but not reliably reproducible) where the semi-sync replicas of a newly promoted master go into some zen-trance and just seem to take their time in replication. meanwhile applying no entries, and growing up with lag. I've seen this without GTID, too.

@rafael what is your `rpl_semi_sync_master_timeout`? We use a short `500ms` so that master fails back to async replication in case of trouble. Maybe that's another route for you to take?

Anyway, `FLUSH BINARY LOGS` is perfectly legitimate to execute.

**Comment by demmer** [comment]
> Yeah, that makes sense to me. It is one of the unfortunate designs of GTID where you need to scan the entire binlog to make the first connection (with Pseudo-GTID you get markers throughout the binlog file and quick jump into the end of file).

Yeah that's what it seemed like to us as well. Thanks for confirming. Now, if mysql were to instead be able to scan the binlog file _backwards_ it seems like it would be more efficient a huge percentage of the time since quite often we would be resuming replication from a point close to the end.

>@rafael what is your rpl_semi_sync_master_timeout? We use a short 500ms so that master fails back to async replication in case of trouble. Maybe that's another route for you to take?

We set `rpl_semi_sync_master_timeout` very high deliberately to fail writes back to the application in the event that we don't have a viable replica.

> Anyway, FLUSH BINARY LOGS is perfectly legitimate to execute.

Cool thanks!

**Comment by shlomi-noach** [comment]
@rafael @demmer even though the issue is closed, please report back with your findings!

**Comment by rafael** [comment]
@shlomi-noach  - We deployed this change to our production environment and the impact was huge. We no longer have errors that are visible to the app during `PlannedReparents`. 

We are thinking in adding this as a hook in orchestrator as well. We see this issue during master failover as well.
