### ISSUE TITLE
Splitclone support transaction streaming protocal

### ISSUE THREAD

**Issue by Johnny-Three** [vitessio/vitess#4198]
Going to  the stage of splitclone on resharding . 
The one destination shard  error says : 
Error received from Stream rpc error : code = ResourceExhausted desc = grpc: received message larger 
than max (71555916 vs  33554432) 
#### Feature Description
Binlog player transport entire transaction size and if there a big transaction size more than grpc limit (64M) . The transport stuck . 
it would be better if vitess support binlog transport transaction by streaming protocol

**Comment by mattlord** [comment]
I'm going to close this for now as with 6.0+ we have the [`vreplication`](https://vitess.io/docs/reference/vreplication/vreplication/) workflows [that should be used instead of `SplitClone`](https://vitess.io/docs/user-guides/historical/vertical-split/). If you feel that you still have a valid use case for `SplitClone` today please let us know. Thanks!
