### ISSUE TITLE
Split Clone / Lookup Backfill chunk size should default to minimum rows rather than number of chunks

### ISSUE THREAD

**Issue by eeSeeGee** [vitessio/vitess#4329]
Currently these worker jobs default to 1000 chunks no matter how big the data set, resulting in very unpredictable sizes depending on the data. A better approach might be to default number of chunks to max int while setting a reasonable minimum chunk size value.

**Comment by mattlord** [comment]
I'm going to close this for now as with 6.0+ we have the [`vreplication`](https://vitess.io/docs/reference/vreplication/vreplication/) workflows [that should be used instead of the legacy Vertical Split work](https://vitess.io/docs/user-guides/historical/vertical-split/). If you feel that you still have a valid use case for the legacy work today please let us know. Thanks!
