### ISSUE TITLE
upgrade vitess will fail by helm

### ISSUE THREAD

**Issue by curls** [vitessio/vitess#4338]
#### Overview of the Issue

When upgrade vitess will fail by helm. the replica always `Init:CrashLoopBackOff`, and found the following issues through the logs:
```
+ mkdir -p /vttmp/bin
+ mkdir -p /vtdataroot/tabletdata
+ cp /vt/bin/mysqlctld /vttmp/bin/
+ cp /bin/busybox /vttmp/bin/
cp: cannot stat '/bin/busybox': No such file or directory
```

Solved step:
Change  _vttablet.tpl file in Line 248 from
```
imagePullPolicy: IfNotPresent
```
to
```
imagePullPolicy: Always
```

becase we need always to pull the latest init-mysql image

**Comment by trevex** [comment]
I can confirm, we encountered the same problem.

**Comment by derekperkins** [comment]
Glad that solved it for you. I switch the `imagePullPolicy` to `Always` when I'm testing, but I'm not sure if it should be in the chart. I think we just need to start doing real versioning. I haven't done any helm chart versioning because until the last few weeks, I wasn't even sure if anyone else was even using it. :) Also, the core Vitess project doesn't have a good versioning scheme and we don't have specific Docker tags set up, which makes it hard to coordinate. I think we're going to set up a cron job to auto tag once a day or something so we can at least have some tags to choose from.

**Comment by trevex** [comment]
Versioning would be a good call :+1: 

Maybe the helm chart could be upstreamed into a helm charts repository as well. While this is not a use-case for us, because we can not use Tiller for security reasons, it might help other users.
