### ISSUE TITLE
vexplain statement

### ISSUE THREAD

**Issue by acharis** [vitessio/vitess#4448]
it would be great if developers could get the vitess execution plan for a statement.
this is different from vtexplain because it's running against a real live vitess installation.
we should probably also include the mysql explain results as well.

note that i'm thinking this is v-explain, not vex-plain

**Comment by derekperkins** [comment]
@acharis I've been wanting the exact same thing and have been meaning to post an issue. The workflow of going to vtgate output with query plans / stats and then hunting for your query is very tedious. This would be fantastic.

Implementation wise, I don't think we necessarily need to put a ton of work into formatting the output. I'd be happy with a giant dump into a single cell like `SHOW ENGINE INNODB STATUS`.

**Comment by demmer** [comment]
Doing this in a way that just dumps out some representation of the vtgate query plan would be pretty trivial.

But this wouldn't _actually_ tell you what mysql queries would execute, since the vttablet itself has its own query planner and rewriter. A slightly more advanced implementation would augment the planner / executor with an `explain` option so that the queries would be routed to each tablet as per usual, where they would be query planned but not executed, more like what vtexplain does. Now, for complicated queries (lookup vindex, cross-shard joins, sequences, etc), the actual vtgate behavior depends on the contents of subqueries so this becomes harder to model without fake rows coming back...

So probably just dumping the vtgate query plan makes the most sense.

**Comment by dweitzman** [comment]
Might be useful to have a way to run a query and get back a log of what shards & tablets it routed to as it executed.

**Comment by derekperkins** [comment]
Currently I just have a hacked together command that executes queries on all shards if I need to find out which shard a row lives on. This would be very helpful.

Similarly, I would also like to have some shard `GROUP BY` commands, so I could run queries like `select VITESS_SHARD, count(*) from tbl`, but that's for another issue.

**Comment by demmer** [comment]
++ To that idea -- we talked about similar things at some point ages ago.

Exposing the shard and/or keyspace id as a queryable primitive would also enable cross-shard paginated queries in ways that are inefficient today.

**Comment by harshit-gangal** [comment]
There is initial code to provide vitess plans with explain statement #6110
