### ISSUE TITLE
Zookeeper DNS names are never refreshed without a restart

### ISSUE THREAD

**Issue by tirsen** [vitessio/vitess#4454]
We're having regular issues in Kubernetes when we restart the stateful set for our Zookeeper cluster. This means the service resolves to new IP addresses. Unfortunately Vitess contains code that resolves the DNS names to IP addresses at upstart and then never refresh them ever again without a restart.

This is the code (go/vt/topo/zk2topo/zk_conn.go:386):
```
// resolveZkAddr takes a comma-separated list of host:port addresses,
// and resolves the host to replace it with the IP address.
// If a resolution fails, the host is skipped.
// If no host can be resolved, an error is returned.
// This is different from the Zookeeper library, that insists on resolving
// *all* hosts successfully before it starts.
func resolveZkAddr(zkAddr string) ([]string, error) {
	parts := strings.Split(zkAddr, ",")
	resolved := make([]string, 0, len(parts))
	for _, part := range parts {
		// The Zookeeper client cannot handle IPv6 addresses before version 3.4.x.
		if r, err := netutil.ResolveIPv4Addrs(part); err != nil {
			log.Warningf("cannot resolve %v, will not use it: %v", part, err)
		} else {
			resolved = append(resolved, r...)
		}
	}
	if len(resolved) == 0 {
		return nil, fmt.Errorf("no valid address found in %v", zkAddr)
	}
	return resolved, nil
}
```

This code has already caused us one major outage (run `git blame` to see how). Can we just get rid of it?

**Comment by sougou** [comment]
Wow. We need to delete this pronto. I bet the original code predates the cloud. Blame only showed me that this was copy-pasta from somewhere else.

**Comment by sjmudd** [comment]
I bumped into this and had the same issue. I got feedback from @sougou and others that we were doing it wrong as the zookeeper endpoints should never change.
And partly as a result of this I've just completed moving from zookeeper to etcd where the new cluster end points will never change. However, in my case I was always using hostnames as end points and the hostnames changed. I'm now using a etcd cluster end point which should resolve to ip addresses which over time may change. That should work. To some extent this seems to be the same here. If you use names that never change (zookeeper endpoint names, not ip addresses) you should be ok?

**Comment by msolo** [comment]
That code in resolveZkAddr can be deleted since you have switched to the native Go zookeeper client. The original reason resolveZkAddr is to mask a bug in the zookeeper C library - it too caches the DNS name indefinitely, but in an opaque way to Go.

If you want a stable, production-grade zookeeper, you can find better versions here:

https://github.com/msolo/go-zookeeper

https://github.com/msolo/zookeeper/tree/msolo-release-3.5.3

Unfortunately, the upstream Go zookeeper client is abandonware, but I've been maintaining this version as well as numerous server fixes with my current colleagues.

**Comment by tirsen** [comment]
Perfect. Should we also switch to @msolo’s fork?

**Comment by deepthi** [comment]
> Perfect. Should we also switch to @msolo’s fork?

I'm looking into that

**Comment by msolo** [comment]
@deepthi Looking at the commit history, there are potentially two diff that we need to backport in terms of max packet sizes with large watch lists. In general, the msolo version has a lot of data races and operational fixes that have been revealed by running at large scale for a while.

We had generally ignored the upstream version since we had no luck submitting pull requests or having email conversations. At this point, a couple of minor refactorings will make for some tricky merging if I try to rebase since they duplicate fixes we made. I will likely have more luck cherry-picking the ones that fix new issues.

**Comment by sougou** [comment]
Reopening this issue. I think we should use @msolo's client patches.

**Comment by deepthi** [comment]
From @msolo, some months ago:
"z-division is the better one. I'm trying to coordinate all the patches and take more contributors and it felt better to do that under an org umbrella."

https://vitess.slack.com/archives/C0PQY0PTK/p1552580860609500?thread_ts=1552485634.534100&cid=C0PQY0PTK
