### ISSUE TITLE
Command set sql_mode='x' fails in vitess

### ISSUE THREAD

**Issue by morgo** [vitessio/vitess#5002]
#### Overview of the Issue

It is common for ORMs and packaged apps to explicitly `set sql_mode=x` when first connecting to MySQL.  For example laravel was mentioned in #4387 (and a workaround in laravel was created).

But the issue is quite common, I know [Wordpress](https://github.com/WordPress/WordPress/blob/a571a7d621e513acf8ff195be188a61876fb4331/wp-includes/wp-db.php#L833-L843) and [Drupal](https://github.com/drupal/drupal/blob/14026e145263a822f7a2c0ce23ca7a94c65309c3/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php#L455-L465), for example, will `set sql_mode=x`' (where x is a list of modes they support).

This SQL mode is also set by the Diesel ORM:
```
set sql_mode=(select concat(@@sql_mode, ',PIPES_AS_CONCAT') from dual);
ERROR 1105 (HY000): vtgate: http://morgox1:15001/: invalid syntax: (select concat(@@sql_mode, ',PIPES_AS_CONCAT') from dual)
```

(It is the set part of the statement that fails. The query construction is fine.)

#### Reproduction Steps

This is one issue of likely others where drivers create initial chatter commands. We should find a way to build a test-suite to make sure that the common use cases are covered.

**Comment by morgo** [comment]
@sougou This is something we chatted about today - where `SESSION` context is not available in Vitess because of the connection pooling to the backend.  One option is to use a `SET_VAR` hint, or a multi-command statement to push the options to the server with the query...  but that could reduce throughput.

**Comment by PrismaPhonic** [comment]
I had experienced this issue when trying to use diesel's client command `setup` which connects to a mysql database, looks for a migrations table, and if not found creates it:

```sh
$ diesel setup
Creating database: bobsaget
vtgate: http://libellis-popsicle-gcpuswest2a-vtgate-b2ab0493-566d8cb88-ltnl8:15000/: invalid syntax: (select CONCAT(@@sql_mode, ',PIPES_AS_CONCAT') from dual)
```

**Comment by dkhenry** [comment]
The diesel setup is particularly difficult, since its the result of a query. I looked into this with @PrismaPhonic last week and the issue was the Set statement does not generate a query plan and can't execute queries. Also since @@sql_mode is a session variable the correct thing to query would be the SET_VAR or SuperSession to see what it is. 

We can make the set statement work by passing it though as an warning that nothing was set, but again for the diesel setup the variable it is setting alters the query dialect so it would really need to be passed all the way through, and supported by the parser.

**Comment by harshit-gangal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Support Set Statements](https://trello.com/c/l7N3HbtN/1-support-set-statements)

**Comment by harshit-gangal** [comment]
This works now #6107
