### ISSUE TITLE
Question about the value of max_binlog_cache_size

### ISSUE THREAD

**Issue by hh-project-config** [vitessio/vitess#5056]
Thanks for providing this useful [container](https://hub.docker.com/r/vitess/mysqlctld). 

I am doing a research aiming at finding issues in configuration files. I have a question about one MySQL config: `max_binlog_cache_size`. It seems the [official document](https://dev.mysql.com/doc/refman/8.0/en/replication-options-binary-log.html#sysvar_max_binlog_cache_size) says "The maximum recommended value is 4GB; this is due to the fact that MySQL currently cannot work with binary log positions greater than 4GB."

However, the default value is 18446744073709551615, which is much larger than the recommended value. 

Shall we change the value to 4GB? 
Thanks!

**Comment by morgo** [comment]
Because this is a maximum size (and not a prealloc etc) I am not sure there is a strong use case to change it _unless_ on an embedded system. Vitess has some further protection against using a lot of memory here because modifications are limited to 10K rows by default.

I have created an issue for reviewing config files in https://github.com/vitessio/vitess/issues/4990 - I plan to look at it after https://github.com/vitessio/vitess/pull/4987 merges.

As a general strategy, I plan to use MySQL's default values unless there is a strong use-case to override. In some cases (sort-buffer, sql-mode, character-set) the usage of the setting or the best value changes through the versions. So if we make a change over upstream, there should be a strong use case because we have to be prepared to maintain it. That is, even if I agree with you that in this specific case the documentation is a bit weird :-)

**Comment by hh-project-config** [comment]
Yes, I agree. They actually have acknowledged the bug but haven't fixed it https://bugs.mysql.com/bug.php?id=94487. Maybe it takes a long time for the official to make a change.

**Comment by morgo** [comment]
I am going to close this issue now, as this is a problem for upstream MySQL to resolve.
