### ISSUE TITLE
mysqlctld: allow setting flags / env vars for mysqld

### ISSUE THREAD

**Issue by derekperkins** [vitessio/vitess#5466]
We just added tcmalloc / jemalloc to the lite build #5444, but as currently constituted, they can't be easily used. `malloc-lib` is a `mysqld_safe` only option, and for systems without `mysqld_safe` like the default Percona images, there is no way to propagate `LD_PRELOAD` into the child mysqld process.

As discussed with @aquarapid at Kubecon, the only workaround available now is to move `mysqld` and set `mysqld` to execute a shell with `LD_PRELOAD` set, as shown below. It would be nice to have that inherit the parent environment or otherwise allow for variables to be set.

```
#!/bin/bash
export LD_PRELOAD="/usr/lib64/libtcmalloc.so.4"
/usr/sbin/mysqld_orig "$@"
```

**Comment by morgo** [comment]
It would be good to use an `LD_PRELOAD` for the testsuite as well https://github.com/vitessio/vitess/issues/5007

**Comment by neowulf** [comment]
I'd like to take up this issue. Is the following the right way to go about it?

1. Is it just a matter of appending the environment variable LD_PRELOAD [similar to how LD_LIBRARY_PATH is added to the environment](https://github.com/vitessio/vitess/blob/a6fcbc80cb64e7ff765770a37a9b42e8b36c8601/go/vt/mysqlctl/mysqld.go#L374) before `mysqld` is executed?
2. This change is environment specific. Did we want to support Mac OS by providing an alternate method?
3. Preparation of the environment array can also be refactored into a separate function within `mysqld.go`

**Comment by deepthi** [comment]
cc @morgo

**Comment by morgo** [comment]
> I'd like to take up this issue. Is the following the right way to go about it?
> 
> 1. Is it just a matter of appending the environment variable LD_PRELOAD [similar to how LD_LIBRARY_PATH is added to the environment](https://github.com/vitessio/vitess/blob/a6fcbc80cb64e7ff765770a37a9b42e8b36c8601/go/vt/mysqlctl/mysqld.go#L374) before `mysqld` is executed?

Yes

> 2. This change is environment specific. Did we want to support Mac OS by providing an alternate method?

The path will vary on linuxes too. So as long as we accept it as a full path, I believe it should be cross platform.

> 3. Preparation of the environment array can also be refactored into a separate function within `mysqld.go`

I will let you use your judgement since it will be easier to understand when viewing the code. But yes - the code is getting a little complicated. I also think that it should do better checking and suggest that mysqld may not have started because of an apparmor / selinux issue. We recently adding checking inside the wrapping shellscripts: https://github.com/vitessio/vitess/pull/5573 -- but I believe this should be done in the go program instead.
