### ISSUE TITLE
Python error when running bootstrap.sh

### ISSUE THREAD

**Issue by jiameixie** [vitessio/vitess#5540]
When filing a bug, please include the following headings if
possible. Any example text in this template can be deleted.

#### Overview of the Issue
When running 
installing Selenium latest
Traceback (most recent call last):
  File "/usr/bin/virtualenv", line 11, in <module>
    load_entry_point('virtualenv==15.1.0', 'console_scripts', 'virtualenv')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 25, in <module>
    import distutils.sysconfig
ModuleNotFoundError: No module named 'distutils.sysconfig'
ERROR: Selenium build failed

#### Reproduction Steps
Build dockerfile for mysql57 on aarch64. This issue doesn't always occur.
Run ./bootstrap.sh

#### Operating system and Environment details
- Operating system (output of `cat /etc/os-release`):Debian 9
- Kernel version (output of `uname -sr`): Linux 4.15.0-45-generic
- Architecture (output of `uname -m`):aarch64

#### Solution
Add  PYTHONPATH=‘’  before $VIRTUALENV "$dist" in function install_selenium. Or maybe the installment pymock should be put at the end

**Comment by morgo** [comment]
We are in the process of converting the tests from Python to Go (and will in the next few months remove Python completely).

I updated the [build guides](https://vitess.io/docs/contributing/build-on-ubuntu/) today to recommend running `make tools` instead of `./bootstrap.sh` (which disables installing Python dependencies). So I am inclined to mark this issue as "Won't fix", but please feel free to reopen if you disagree. I would be happy to have a discussion about it.
