### ISSUE TITLE
Run ./101_initial_cluster.sh get  a error

### ISSUE THREAD

**Issue by guihouchang** [vitessio/vitess#5564]
which: no mysqld in (/home/vit/vitess-4.0.1-0629f0d/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)

I have mysql in /usr/bin

**Comment by morgo** [comment]
You probably have the mysql client, but not the mysql server. Usually the MySQL server will be in /usr/sbin (which might not be in your path). In https://github.com/vitessio/vitess/pull/5506 I added a patch so that it will force-search the standard location.

Did you mind trying the latest master, and double checking?
