### ISSUE TITLE
Replace VTTOP variable with VTROOT

### ISSUE THREAD

**Issue by neowulf** [vitessio/vitess#5668]
The [docs] mention setting `VTTOP` env variable containing `$VTROOT`. Looking at the `vitess` codebase, there are only couple places referring to `VTTOP`.

*Suggested Fix*

1. Replace VTTOP env variable with VTROOT in Makefile
1. Rename `vttop` variable to `vtroot` in `run.py`
1. Create a separate PR and update [docs] and [zh-docs] in `vitessio/website`.

[docs]: https://github.com/vitessio/website/blame/prod/content/en/docs/get-started/local.md#L67
[zh-docs]: https://github.com/vitessio/website/blame/prod/content/zh/docs/get-started/local.md#L43

**Comment by morgo** [comment]
This was recently fixed in https://github.com/vitessio/vitess/pull/5527

The docs will need to be updated, but they are technically not out of date yet (since the changes in master have not made it into a release yet).

But thank you for the reminder. We will have to update the docs with Vitess 5.0 shipping in a few weeks time.

**Comment by morgo** [comment]
I am working on an update in https://github.com/vitessio/website/pull/383

**Comment by morgo** [comment]
I believe this is now fixed, so I am going to close this issue. But please feel free to re-open if you discover additional cases that need updating.
