### ISSUE TITLE
can vitess be configured as non-sharding？

### ISSUE THREAD

**Issue by Jacklli** [vitessio/vitess#5731]
can vitess be configured as non-sharding？

can vitess be configured as direct send to mysql so the sql can be 100% Compatible with mysql？

- [Vitess User Guide](https://vitess.io/user-guide/introduction/)
- Any other questions can be asked in the community [Slack workspace](https://vitess.io/slack)

**Comment by morgo** [comment]
@Jacklli we call this V2 routing, which is deprecated and soon to be removed.

The problem is that if Vitess does a direct-send without parsing, it would need to do dedicated connections. The connection pool is important for scalability, and creating a migration path from unsharded to sharded clusters.

**Comment by aquarapid** [comment]
Since early 2020 we have added dedicated connections to support (some) session variables;  but the query still passes via the Vitess parser, so compatibility support is not 100%, but should be much improved in the last 18+ months.

As to the unsharded part, yes, you can run with a single database (shard) behind Vitess and no vSchema (sharding schema).
