### ISSUE TITLE
Vitess does not support ordering on character fields for sharded keyspace queries

### ISSUE THREAD

**Issue by aquarapid** [vitessio/vitess#5740]
You can only perform sharded keyspace queries with an ORDER BY field that is a binary equivalent type (e.g. VARBINARY, datetime, INTEGER, etc).

Ordering by a CHAR or VARCHAR field fails, and isn't present in unsupported_cases.txt (this was unexpected to me):

SQL schema:
```
$ cat schema.sql 
CREATE TABLE t1 (
  id int(11) NOT NULL,
  name varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;
```

vSchema:
```
$ cat vschema.json 
{
    "ks1": {
        "sharded": true,
        "tables": {
            "t1": {
                "column_vindexes": [
                    {
                        "column": "id",
                        "name": "hash"
                    }
                ]
            }
        },
        "vindexes": {
            "hash": {
                "type": "hash"
            }
        }
    }
}
```

Test:
```
$ sh -x test.sh
+ vtexplain -schema-file schema.sql -vschema-file vschema.json -shards 2 -sql 'SELECT name, id FROM t1 ORDER BY t1.name ASC'
ERROR: vtexplain execute error in 'SELECT name, id FROM t1 ORDER BY t1.name ASC': types are not comparable: VARCHAR vs VARCHAR
```

**Comment by aquarapid** [comment]
OK, looking at the test cases;  it makes sense why this case isn't in unsupported_cases.txt ;  those are emitted by the planbuilder, while this error gets generated by the vtgate engine.

Also, to be clear, this affects columns of type CHAR, VARCHAR and TEXT.

**Comment by gedgar** [comment]
Per @sougou, this is because vtgate cannot (yet) mimic the collation rules of MySQL. You can declare the column type in the vschema, which will make vtgate rewrite the query using `weight_string`, allowing you to merge-sort on a scatter-gather. 

```
"columns": [
   {
      "name": "name",
      "type": "VARCHAR"
   }
```

**Comment by aquarapid** [comment]
Ah;  we should do this automatically (without the vSchema) then?

**Comment by teejae** [comment]
yea that seems derivable from the schema?

**Comment by teejae** [comment]
@sougou how does the weight_string get forced in if there's a column in the vindex? i don't see any obvious code.

**Comment by GuptaManan100** [comment]
Proposed solutions for ordering varchar and other such columns

- Add the columns to the vschema and specify it as authoritative columns. Vtgate will then use weight strings to sort them. This will require us to add SQL commands to add the columns to the vschema and also to make the table authoritative. Something like `ALTER VSCHEMA ADD COLUMNS (column_list) TO keyspace.tableName`  and `ALTER VSCHEMA MAKE TABLE keyspace.tableName AUTHORITATIVE`
  - PROs - will need to do this eventually in the long run
  - CONs - will take time to implement and rails testing will be stalled till then
- Add weighted_strings for all the columns that we do not know the types for and use it only in the case for VARCHAR, TEXT and such data types.
  - PROs - Make Vitess more usable as this would allow ordering all types of columns. Users need not worry about the data types for using ordering values. Inline with the ideology that everything works out of the box without much setup
  - CONs - adds overhead to all the queries that use order by. User needs to be aware of authoratative columns functionality to prevent this overhead
- Run a field query during planning phase to find the column type in case order by clause is specified and add weight strings in case of non-numeric columns
  - PROs - Things will work out of the box and all types of sorting will be supported. For numeric data, we will also prevent the overhead of weight strings
  - CONs - adds an overhead of an additional query for all queries using order by. User needs to be aware of authoratative columns functionality to prevent this overhead

The team has decided to go forward with option 2 so that we can support ordering of any columns. Also advanced users can still specify authoritative columns to prevent the additional overhead of weighted strings in numeric columns
