### ISSUE TITLE
RFC: add "ignore_nulls" option to lookup vindexes

### ISSUE THREAD

**Issue by sougou** [vitessio/vitess#6147]
There are situations where the `from` columns of a lookup vindex can be null. Such columns cannot be inserted in the lookup due to the uniqueness constraints of a lookup. There are use cases where such a thing can be a requirement.

If the input value of any of the columns is null, we could skip the creation of the lookup row. This does will not cause problems because such rows are not findable through those columns, but they could be found by other criteria (like primary vindex).

In order to maintain backward compatibility, we'll introduce this feature behind an additional param to vindex: "ignore_nulls". If set, then no lookup row will be created (or deleted) for such owner rows.

**Comment by harshit-gangal** [comment]
Instead of lookup table having lookup columns as primary key, can they not be changed to unique key. That way null values would be allowed to be inserted.

**Comment by ochotinun** [comment]
we are also running into an error when the sharded lookup table has only 2 columns: UK and rowspace_id. In this case it has a vindex on the first column. When the value of the first column is null, Vitess has an error mapping the column to a shard.
ERROR 1105 (HY000): vtgate: http://f81ee823dbab:14999/: execInsertSharded: getInsertShardedRoute: lookup.Create: could not map [NULL] to a keyspace id

**Comment by yborovikov** [comment]
> Instead of lookup table having lookup columns as primary key, can they not be changed to unique key. That way null values would be allowed to be inserted.

while you _can_ insert rows with `null`s this way, the essence is that you _don't want_ rows with `null`s there (for `unique` vindex lookups), at all.

that's because each `null` is unique and not equal to anything hence these lookup rows can neither be used for lookups by the unique key (there will never be a single match) nor be addressed themselves (e.g. when one of the lookup columns gets modified in the main table and you try to reflect that in the lookup row or when a row is deleted from the main table - the previous row will never be updated or deleted, respectively).

**Comment by sougou** [comment]
Since inserting null values is hazardous, I'll be changing the existing behavior to fail if any of the input values are null. This is safe because there is no chance of this to have worked before.

If the ignore_nulls is enabled, then those inputs will be removed from the insert.

**Comment by ochotinun** [comment]
adding Gopal for tracking.
Olga

**Comment by ochotinun** [comment]
adding Guoning
Olga
