### ISSUE TITLE
Suggestion: simplify vreplication schema, thereby visibility and scripting

### ISSUE THREAD

**Issue by shlomi-noach** [vitessio/vitess#6352]
I happened to read the [vreplication doc](https://vitess.io/docs/reference/features/vreplication/), which illustrates the steps to setting up vreplication. The section "Creating a stream" says:

> It’s generally easier to send the VReplication command programmatically instead of a bash script. This is because of the number of nested encodings involved

Specifically `source` is a protobuf representation of the stream source, and has nested fields, including queries, leading to complicated escape rules.

However, it seems to me like `source` is well defined. We can reduce complexity by adding the following columns to the `vpreplication` table:

- `keyspace`: text
- `shard`: text
- `rule_match`: text
- `rule_select_columns`: text
- `rule_select_from_table`: text
- `rule_select_where_clause`: text
- `rule_select_group_by_clause`: text

Note: the above assumes there is a single filter rule. My understanding is that multiple rules are supported, but that a single rule is more common.

Note: I chose to break the `select` query into distinct parts because the `select` query is very restricted. The breakdown helps in restricting th equery.

As example, the `source` value of

    keyspace:"user" shard:"-80" filter:<rules:<match:"sales" filter:"select pid, count(*) as kount, sum(price) as amount from uorder group by pid" > >

Will map to these column values:

- `keyspace`: `user`
- `shard`: `-80`
- `rule_match`: `sales`
- `rule_select_columns`: `pid, count(*) as kount, sum(price) as amount`
- `rule_select_from_table`: `uorder`
- `rule_select_where_clause`: `` (empty string)
- `rule_select_group_by_clause`: `pid`

Another example: the following heavily escaped command:

```shell
cmd = [
  './lvtctl.sh',
  'VReplicationExec',
  'test-200',
  """insert into _vt.vreplication
  (db_name, source, pos, max_tps, max_replication_lag, tablet_types, time_updated, transaction_timestamp, state) values
  ('vt_keyspace', 'keyspace:"lookup" shard:"0" filter:<rules:<match:"uproduct" filter:"select * from product" > >', '', 99999, 99999, 'master', 0, 0, 'Running')""",
]
```

Can be reduced to:
```shell
cmd = [
  './lvtctl.sh',
  'VReplicationExec',
  'test-200',
  """insert into _vt.vreplication
  (db_name, keyspace, shard, rule_match, rule_select_columns, rule_select_from_table, pos, max_tps, max_replication_lag, tablet_types, time_updated, transaction_timestamp, state) values
  ('vt_keyspace', 'lookup', '0', 'uproduct', '*', 'product', '', 99999, 99999, 'master', 0, 0, 'Running')""",
]
```

My suggestion is that `source` column remains for backwards compatibility, and keeps being used. However, if `keyspace`, `shard`, are nonempty, they override whatever's defined in `source`. If `rule_match` is non empty, then all of the `rule_select_*` columns are applied onto the `source` value (some of them may be empty and still they should override the `source` value).

Affected files would be:

- https://github.com/vitessio/vitess/blob/e3c54bc3710779b25a5f157e08c1bb41ab21a2a9/go/vt/binlog/binlogplayer/binlog_player.go#L495-L522 (table definition)
- https://github.com/vitessio/vitess/blob/e3c54bc3710779b25a5f157e08c1bb41ab21a2a9/go/vt/vttablet/tabletmanager/vreplication/controller.go#L102 (read the new columns and override `source`)
- various test files

If any of the above makes sense, I'm happy to try implementing this by way of practice and initial contribution.

**Comment by shlomi-noach** [comment]
Does anyone have any thoughts?

**Comment by sougou** [comment]
There were a few factors that influenced this decision:
* Using a rigid schema has mostly caused problems in the past for us. For example, there are fields like max_tps that are deprecated, but they're just hanging around. Then we burnt ourselves adding a new column. When someone rolled back an upgrade, all hell broke lose, because the old code didn't know how to deal with the new column.
* With a single proto field that has multiple values, it's been easier to add/remove fields, and their default behavior mostly works correctly if there are version mismatches.
* The table itself is a low level one. Only "experts" are supposed to be directly creating rows in it. End users should be using higher level tools like `MoveTables`, `Reshard`, etc.
* If you really want to write your own vrep, there is a tool you can use to generate the command: https://github.com/vitessio/contrib/blob/master/vreplgen/vreplgen.go.
* I kept the representation as human readable. That's come in handy for troubleshooting.

Here are some counterpoints:
* We previously hand-coded the schema upgrades, which was bug-prone. I now have a new package to facilitate this: https://github.com/vitessio/vitess/blob/master/go/vt/withddl/withddl.go.
* We plan to perform a one-time migration of the table to deprecate all old fields, convert some columns to blobs, etc.
* We can consider pulling some core fields out to their own columns during this process.

**Comment by shlomi-noach** [comment]
Awesome, thanks for sharing all this information! I'll proceed to close this issue.
