### ISSUE TITLE
Materialize workflows from sharded to sharded keyspaces can setup unused vreplication flows, showing errors.

### ISSUE THREAD

**Issue by aquarapid** [vitessio/vitess#6389]
Scenario:

  * We are copying a table from a sharded keyspace to another sharded keyspace
  * The target keyspace has more shards (say 4) than the source keyspace (say 2)
  * The table being copied has the same sharding key in the source keyspace as in the target keyspace, i.e. the vschema for both tables are identical.

We are doing the copy via the `Materialize` vtctlclient command, e.g. something like:

```vtctlclient -server localhost:15999 Materialize '{ "workflow": "a1", "source_keyspace": "source", "target_keyspace": "target", "table_settings": [ { "target_table": "t1", "source_expression": "select * from t1" } ] }'```

The problem observed is:
  * vreplication rules will be created for every source shard on every target shard (i.e. 2 vreplication rules create on each of the 4 target shards).
  * However, one of these rules will have no rows to copy, since the new shard (assuming the normal even keyspace split) is fully covered by only one of the source shards.
  * We do not handle this case well, and some weirdness ensues, including errors in this "do nothing" vreplication stream.

Possible solutions:
  * Identify cases like this upfront, and just don't create the unnecessary vreplication streams.
  * If a stream like this does get setup, handle the case of zero rows to copy cleanly, without errors.

**Comment by rohit-nayak-ps** [comment]
I was unable to reproduce this. I have tried with different variations including source shards "-80,80-" and target shards "-40,40-80,80-c0,c0-". I tried MoveTables
and also the Materialize command specified here. I also tested with empty tables, so none of the targets had data and also with a few other keyspace id combinations where
one or more targets had no data from a source.

Related log attached where two shards have no sources. There are two streams in each target from the two source shards. The streams start as expected and target shards have the appropriate data.
I tried with 1 row per target, zero rows in the source etc so that there are situations where the copy phase will not find data.

```
vttablet.rohit-ubuntu.rohit.log.INFO.20200710-165549.31485:I0710 16:56:56.743885   31485 vcopier.go:192] Copying table coal, lastpk: <nil>
vttablet.rohit-ubuntu.rohit.log.INFO.20200710-165549.31485:I0710 16:56:56.745189   31485 vcopier.go:192] Copying table coal, lastpk: <nil>
vttablet.rohit-ubuntu.rohit.log.INFO.20200710-165549.31485:I0710 16:56:56.859471   31485 vcopier.go:297] Copy of coal finished at lastpk: map[]
vttablet.rohit-ubuntu.rohit.log.INFO.20200710-165549.31485:I0710 16:56:56.931208   31485 vcopier.go:297] Copy of coal finished at lastpk: map[lastpk:type:VARBINARY value:"fields:<name:\"cid\" type:INT32 > rows:<lengths:4 values:\"9999\" > " ]
vttablet.rohit-ubuntu.rohit.log.INFO.20200710-165554.32737:I0710 16:56:56.703818   32737 vcopier.go:192] Copying table coal, lastpk: <nil>
vttablet.rohit-ubuntu.rohit.log.INFO.20200710-165554.32737:I0710 16:56:56.705478   32737 vcopier.go:192] Copying table coal, lastpk: <nil>
vttablet.rohit-ubuntu.rohit.log.INFO.20200710-165554.32737:I0710 16:56:56.768080   32737 vcopier.go:297] Copy of coal finished at lastpk: map[lastpk:type:VARBINARY value:"fields:<name:\"cid\" type:INT32 > rows:<lengths:4 values:\"9999\" > " ]
vttablet.rohit-ubuntu.rohit.log.INFO.20200710-165554.32737:I0710 16:56:56.838604   32737 vcopier.go:297] Copy of coal finished at lastpk: map[]
```

Maybe I am not testing with the same setup that caused the bug.

**Comment by aquarapid** [comment]
I am fine with closing it;  and re-opening if we run into it again.
