### ISSUE TITLE
Fix where clause in information schema with correct database name

### ISSUE THREAD

**Issue by harshit-gangal** [vitessio/vitess#6599]
#### Overview of the Issue

The query sent down from VTGate to Vttablet does not replace the where clause of the information schema queries for table_schema = 'keyspace' to table_schema = 'databasename'

#### Reproduction Steps

Steps to reproduce this issue, example:

1. Deploy the following `vschema`:

    ```javascript
    {
      "sharded": false,
      "tables": {
      }
    }
    ```

2. Run 
```
mysql> SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'commerce' AND TABLE_NAME LIKE '%' HAVING TABLE_TYPE IN ('TABLE','VIEW',null,null,null) ORDER BY TABLE_TYPE, TABLE_SCHEMA, TABLE_NAME;
Empty set (0.02 sec)

mysql> SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'commerce' AND COLUMN_NAME LIKE '%' ORDER BY TABLE_SCHEMA, TABLE_NAME, ORDINAL_POSITION;
Empty set (0.00 sec)
```
Both the query returns empty result test

#### Binary version
master

#### Operating system and Environment details
Sprint boot application with mysql 8.0

**Comment by harshit-gangal** [comment]
Support added via #6638

**Comment by yborovikov** [comment]
@harshit-gangal this is a (very) breaking change.

**Comment by harshit-gangal** [comment]
@yborovikov can you explain why this is breaking change? Previously the query did not give any result. Now it is handled.

**Comment by yborovikov** [comment]
sure: previously a query like `SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'vt_commerce';` returned a result. now it doesn't.

**Comment by harshit-gangal** [comment]
Yes, this has changes in vtgate and vttablet. We will make this feature available in two step because now it depends on upgrade order of Vitess cluster.

**Comment by yborovikov** [comment]
not sure how any sequencing of vitess upgrades can not break the customers that use queries like `... FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'vt_SOMENAMESPACE';`.

current client code _has_ to prefix the namespace with `vt_` - and the change rendered these queries broken. neither we can _not_ prefix the namespace - since it won't work with current installations of vitess.

the change itself is reasonable - customers shouldn't be aware of internal (to vitess and mysql) re/naming conventions.
