### ISSUE TITLE
Optimize multi-value IN clauses referencing multi-column lookup vindexes

### ISSUE THREAD

**Issue by aquarapid** [vitessio/vitess#6609]
Today, we have optimized shard access of `SELECT` statements with `IN` clauses specifying a list of vindex keys.

However, if you have a multi-column lookup vindex, and have queries like:

```
select * from t1 where (c2,c3) in ((1,2), (5,6), (6,7));
```

This will get scattered across all shards.  We should see if these can be optimized.

Full example:

 * First, use the local examples to setup a sharded keyspace (customer):
```
$ cd examples/local/
$ for i in `ls -1 [1-3]*.sh` ; do echo $i ; ./$i ; sleep 5 ; done
.
.
.
$ vtctlclient -server localhost:15999 ListAllTablets
zone1-0000000100 commerce 0 master localhost:15100 localhost:17100 [] 2020-08-21T18:07:48Z
zone1-0000000101 commerce 0 replica localhost:15101 localhost:17101 [] <null>
zone1-0000000102 commerce 0 rdonly localhost:15102 localhost:17102 [] <null>
zone1-0000000300 customer -80 master localhost:15300 localhost:17300 [] 2020-08-21T18:10:34Z
zone1-0000000301 customer -80 replica localhost:15301 localhost:17301 [] <null>
zone1-0000000302 customer -80 rdonly localhost:15302 localhost:17302 [] <null>
zone1-0000000400 customer 80- master localhost:15400 localhost:17400 [] 2020-08-21T18:10:35Z
zone1-0000000401 customer 80- replica localhost:15401 localhost:17401 [] <null>
zone1-0000000402 customer 80- rdonly localhost:15402 localhost:17402 [] <null>
```

 * Now, apply schema:
```
$ cat schema.sql 
CREATE TABLE t1 (
    c1 BIGINT NOT NULL,
    c2 BIGINT NOT NULL,
    c3 BIGINT NOT NULL,
    PRIMARY KEY (c1),
    UNIQUE KEY (c2, c3)
) ENGINE=Innodb;

CREATE TABLE lookup_t1 (
    c2 BIGINT NOT NULL,
    c3 BIGINT NOT NULL,
    keyspace_id BINARY(8),
    primary key (c2, c3)
);

$ vtctlclient -server localhost:15999 ApplySchema -sql "$(cat schema.sql)" customer
```
 * Next, apply vschema:

```
$ cat vschema.json 
{
    "sharded": true,
    "vindexes": {
        "hash": {
            "type": "hash"
        },
        "lookup_c2c3": {
            "type": "consistent_lookup_unique",
            "params": {
                "table": "lookup_t1",
                "from": "c2,c3",
                "to": "keyspace_id"
            },
            "owner": "t1"
        }
    },
    "tables": {
        "t1": {
            "columnVindexes": [
                {
                    "column": "c1",
                    "name": "hash"
                },
                {
                    "columns": ["c2","c3"],
                    "name": "lookup_c2c3"
                }
            ],
            "columns": [
                {
                    "name": "c1",
                    "type": "INT64"
                },
                {
                    "name": "c2",
                    "type": "INT64"
                },
                {
                    "name": "c3",
                    "type": "INT64"
                }
            ],
            "columnListAuthoritative": true
        },
        "lookup_t1": {
            "columnVindexes": [
                {
                    "column": "c2",
                    "name": "hash"
                }
            ]
        }
    }
}

$ vtctlclient -server localhost:15999  ApplyVSchema -vschema="$(cat ./vschema.json)" customer
.
.
```
 
 * Clean up and insert data:
```
$ cat init.sql 
truncate lookup_t1;

truncate t1;

insert into t1 values (1,1,2);
insert into t1 values (2,3,4);
insert into t1 values (3,4,5);
insert into t1 values (4,5,6);
insert into t1 values (5,6,7);
insert into t1 values (6,7,8);

$ mysql -u root -P 15306 -h 127.0.0.1 customer -A
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 12
Server version: 5.7.9-Vitess MySQL Community Server - GPL
.
.
.
mysql> source init.sql
Query OK, 0 rows affected (0.12 sec)

Query OK, 0 rows affected (0.23 sec)

Query OK, 1 row affected (0.07 sec)

Query OK, 1 row affected (0.05 sec)

Query OK, 1 row affected (0.06 sec)

Query OK, 1 row affected (0.06 sec)

Query OK, 1 row affected (0.05 sec)

Query OK, 1 row affected (0.05 sec)

mysql>
```

 * Now, you can perform the lookup like:
```
mysql> select * from t1 where (c2,c3) in ((1,2), (5,6), (6,7));
+----+----+----+
| c1 | c2 | c3 |
+----+----+----+
|  1 |  1 |  2 |
|  5 |  6 |  7 |
|  4 |  5 |  6 |
+----+----+----+
3 rows in set (0.00 sec)
```
  and then check the vtgate and tablet query logs to confirm that this is being scattered.  A simpler indication might just be:

```
mysql> explain format=vitess select * from t1 where (c2,c3) in ((1,2), (5,6), (6,7));
+----------+---------------+----------+-------------+------------+----------------------------------------------------------------------+
| operator | variant       | keyspace | destination | tabletType | query                                                                |
+----------+---------------+----------+-------------+------------+----------------------------------------------------------------------+
| Route    | SelectScatter | customer |             | UNKNOWN    | select c1, c2, c3 from t1 where (c2, c3) in ((1, 2), (5, 6), (6, 7)) |
+----------+---------------+----------+-------------+------------+----------------------------------------------------------------------+
1 row in set (0.00 sec)
```

**Comment by aquarapid** [comment]
There was some previous work on this here:  https://github.com/vitessio/vitess/pull/4768

**Comment by sougou** [comment]
There are three options, two of which are complex and hyper-efficient, and one that is simple but good enough. The initial implementation will be the simpler option, but I'll explain all three options here.

## How IN clause works today
If the LHS of an IN clause has a vindex, the analyzer pulls all values of the in clause int the `Values` member. It also replaces the original values with a list var.

At the time of execution, shards are resolved based on the input value. A separate set of bind vars are built for each shard based on what matched. This ensures that the query we send to each shard only contains values that can match for that shard.

## Option 1: Simple and recommended.
The analyzer can detect a tuple based IN clause as different from a simple IN clause. This will result in a new code path and a new route opcode `SelectMultiEqual`. The new code path will extract the vindex keys from the inner tuples and add them as a list to the `Values` member.

The original query will otherwise remain unchanged.

During execution, the engine will use the vindex keys in `Values` to resolve the target shards, and send the original query to all shards.

This approach is slightly inefficient because the entire query is sent to all shards without subsetting the IN clause parts that match a shard.

## Option 2: Nested list vars
We could extend the original approach of replacing the tuple values with a list var. However, this requires bind vars to support tuples of tuples, which it doesn't right now. Changing the `querypb.BindVariables` proto struct to support nested tuples can be a challenge.

## Option 3: Pivoted list vars
There is a proposal to support tuple lists using a pivoted list of bind vars. This allows us to avoid nesting of bind vars, but additional semantics have to be added in the query generator to understand pivoted bind vars. An initial attempt was made for this in #4768. The downside of this approach is that it works only for one level of nesting.
