### ISSUE TITLE
Blacklisted table issue with multiple vtctlclient SwitchWrites

### ISSUE THREAD

**Issue by mdkent** [vitessio/vitess#6793]
#### Overview of the Issue

Successive calls to `vtctlclient SwitchWrites` results in `stopSourceWrites failed: Code: INVALID_ARGUMENT
trying to use two different sets of blacklisted tables for shard`, which then works on retry. Please see the attached logs.

The error message contains both the tables from the previous SwitchWrites call and the tables from the current call.

#### Reproduction Steps

1.  Create a number of MoveTables workflows which each copy a number of tables into a new keyspace
```
vtctlclient MoveTables -workflow=move_main_1 mainunsharded main {"access_notices":{}, "accesses":{}, "account_cancellations":{}, "account_invitations":{}, "account_ownerships":{}, "accounts":{}, "aliases":{}}
<snip>
vtctlclient MoveTables -workflow=move_main_7 mainunsharded main {"receipt_recipients":{}, "receipts":{}, "recipients":{}, "services":{}, "sessions":{}, "tombstones":{}, "topic_merges":{}}
vtctlclient MoveTables -workflow=move_main_8 mainunsharded main {"topic_mergings":{}, "topic_preapproved_clearances":{}, "topic_publications":{}, "topic_spans":{}, "topics":{}, "two_factor_authentication_profiles":{}, "users":{}}
```
2. Once the workflows transition from Copying to Running, try to SwitchWrites over to the new copies:
```
vtctlclient SwitchWrites main.move_main_1
# works as expected

vtctlclient SwitchWrites main.move_main_2
# errors with 'trying to use two different sets of blacklisted tables for shard'
# stopSourceWrites failed: Code: INVALID_ARGUMENT trying to use two different 
# sets of blacklisted tables for shard # mainunsharded/-: [<previous MoveTables>] and [<current MoveTables>]

vtctlclient SwitchWrites main.move_main_2
# works as expected

<repeat>
```

I haven't put together a full reproduction yet.

#### Binary version
7.0.2

#### Operating system and Environment details

- Kubernetes using the vitess-operator from planetscale
- All Aurora backed instances on AWS

#### Log Fragments

https://gist.github.com/mdkent/fe2d5b5b6137a5480eeb2d7b73657cf1

**Comment by rohit-nayak-ps** [comment]
Thanks for the detailed notes. I was able to reproduce this. tldr: the first SwitchWrites cleans up the error (an incorrect side-effect!) and hence the second SwitchWrites succeeds. We will fix the bug asap. 

More details in case you are interested:

1. When we SwitchWrites, we first turn off writes on the source. This is done by adding a "blacklist" record in the topo so that vtgate rejects any queries on the source. Currently there is a limitation that allows only one set of blacklisted tables.
2. Hence the second SwitchWrites fails because the first one created a record for the tables in the move_main_1 workflow and it conflicts when this SwitchWrites tries to add a second one.
3. We have a DropSources command that cleans up the blacklisted tables of a workflow. So you can call that once you are done with SwitchWrites.
Note however that it deletes the source tables by default (or you can rename them using -rename). We are 
going to add a flag to DropSources soon to keep the original data and only cleanup the Vitess artifacts.
4. When the first SwitchWrites fails, it clears the blacklisted rules which it _thinks_ it created, deleting the old rules instead. We will fix this bug by allowing multiple blacklisted table sets. This lets the second SwitchWrites succeed.

As mentioned we will fix it so that the second set of blacklisted tables can be added even if DropSources is not run. For now, as a workaround, you can just continue ignoring the first SwitchWrites error and call it again.
