### ISSUE TITLE
`errCode = 2027, errState = "HY000", errMsg = "decoding parameter value failed: 6167"` with mysql-haskell

### ISSUE THREAD

**Issue by mcronce** [vitessio/vitess#6986]
#### Overview of the Issue
So, I will preface this by saying I have absolutely no idea where "6167" is coming from.  I've scoured the test code, checked vtgate logs, checked vttablet logs, taken a packet capture, converted to hex, reversed the bytes in case of an endianness difference, etc.  Still completely clueless.  I'll attach a pcap showing the failure.

Using good ol' printf debugging, I was able to narrow down the function call to this: https://github.com/planetscale/vitess-framework-testing/blob/master/haskell/mysql-haskell/src/BinaryRow.hs#L201

#### Reproduction Steps
`git clone -b mysql-haskell-narrowed-to-2027-error https://github.com/planetscale/vitess-framework-testing.git`

`cd` into `haskell/mysql-haskell`

Set the following environment variables:
```
VT_PORT
VT_DATABASE
VT_PASSWORD
VT_USERNAME
VT_HOST
```

`docker build -t haskell-mysql-haskell-framework-testing . && docker run --rm -i -e VT_HOST -e VT_PORT -e VT_USERNAME -e VT_PASSWORD -e VT_DATABASE haskell-mysql-haskell-framework-testing`

Observe output similar to:
```
FAIL (0.04s)
  reading env...
  connecting...
  preparing table...      (0.04s)
  testing binary protocol
    ERRException (ERR {errCode = 2027, errState = "HY000", errMsg = "decoding parameter value failed: 6167"})
```

Note that this branch has the `mysql-haskell` test suite narrowed to the minimum required to observe this error.  If you want to run the full suite, `master` will see a bunch of tests succeed before reaching this test case.

#### Binary version
```
Version: c893acd (Git branch 'master') built on Tue Sep 15 05:05:11 UTC 2020 by vitess@5d22aaed795b using go1.13.9 linux/amd64
```

#### Operating system and Environment details
In the vtgate container:
```sh
vitess@mc-test1-mc1local-vtgate-afe64d24-67c76c7d9-vrn8f:/$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

On the host, where I'm running the client:
```sh
[mc@mc-thinkpad src]$ cat /etc/os-release 
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux
```

#### Log Fragments
Nothing relevant :(

**Comment by mcronce** [comment]
pcap:  https://drive.google.com/file/d/1MpVgxRhszcsrT11dxFc5Ua1EkS3SJ5so/view?usp=sharing

**Comment by systay** [comment]
ok, so we’ve made some progress on this, but we have questions…

according to the mysql spec, YEAR values should be encoded using 2 bytes (https://dev.mysql.com/doc/internals/en/binary-protocol-value.html, search for MYSQL_TYPE_YEAR)

but in the wireshark dump we have, it’s easy to see that the year is being encoded as a string:

```
00b0   11 19 3b 00 00 00 00 0c 01 08 00 00 00 07 3b 3b   ..;...........;;
00c0   00 00 00 00 04 31 39 39 39 08 31 32 33 34 35 36   .....1999.123456
00d0   37 38 0c e9 9f a9 e5 86 ac e7 9c 9f e8 b5 9e 08   78..............
```

someone is doing something wrong, that is clear. the questions is: is it Vitess or is it haskell-mysql? are they sending us the data encoded badly because of something we are doing wrong, or is it something they are doing wrong?
according to the spec, a `PREPARE query` call is answered by the server with information about the number and types of output columns, and the number and types of input parameters (https://dev.mysql.com/doc/internals/en/com-stmt-prepare-response.html)

what would help us make sense of it all would be to have a wireshark dump with the same test run but against Vanilla mysql, so we can make sure that haskell-mysql is doing the right thing.

**Comment by mcronce** [comment]
https://drive.google.com/file/d/19HiMsepxOHhT5DD6PtBpDzHpvwg9gdjv/view - this was against MySQL 5.7

**Comment by harshit-gangal** [comment]
This looks like haskell is not following the protocol as per the specs and even the mysql-server is not following it.

MySQL [Spec Link](https://dev.mysql.com/doc/internals/en/binary-protocol-value.html): For Binary Protocol of MYSQL_TYPE_YEAR uint16 is expected
```
ProtocolBinary::MYSQL_TYPE_SHORT, ProtocolBinary::MYSQL_TYPE_YEAR:
Fields
value (2) -- integer

Implemented By
Field_year::send_binary() and Protocol_binary::store_short()

Example

01 00 -- int16 = 1
```

Haskell [Code Link](https://hackage.haskell.org/package/mysql-haskell-0.8.3.0/docs/src/Database-MySQL-Protocol-MySQLValue.html): This intentionally sends YEAR as string and MYSQL_TYPE_YEAR instead of uint16
```
putBinaryField (MySQLYear       n) = putLenEncBytes . L.toStrict . BB.toLazyByteString $
                                        Textual.integral n  -- this's really weird, it's not documented anywhere
                                                            -- we must encode year into string in binary mode!
```

Mysql-Server [Code Link](https://github.com/mysql/mysql-server/blob/ee4455a33b10f1b1886044322e4893f587b319ed/sql/protocol_classic.cc#L3896,L3947): It ignored the type MYSQL_TYPE_YEAR and uses default decoding logic 
```
/**
  Returns the length of the encoded data
   @param[in]  type            parameter data type
   @param[in]  packet          network buffer
   @param[in]  packet_left_len number of bytes left in packet
   @param[out] header_len      the size of the header(bytes to be skiped)
   @param[out] err             boolean to store if an error occurred
*/
static ulong get_ps_param_len(enum enum_field_types type, uchar *packet,
                              ulong packet_left_len, ulong *header_len,
                              bool *err) {
  DBUG_TRACE;
  *header_len = 0;

  switch (type) {
    case MYSQL_TYPE_BOOL:
    case MYSQL_TYPE_TINY:
...
    case MYSQL_TYPE_SHORT:
...
    case MYSQL_TYPE_FLOAT:
    case MYSQL_TYPE_LONG:
...
    case MYSQL_TYPE_DOUBLE:
    case MYSQL_TYPE_LONGLONG:
...
    case MYSQL_TYPE_DECIMAL:
    case MYSQL_TYPE_NEWDECIMAL:
    case MYSQL_TYPE_DATE:
    case MYSQL_TYPE_TIME:
    case MYSQL_TYPE_DATETIME:
    case MYSQL_TYPE_TIMESTAMP:
...
    case MYSQL_TYPE_TINY_BLOB:
    case MYSQL_TYPE_MEDIUM_BLOB:
    case MYSQL_TYPE_LONG_BLOB:
    case MYSQL_TYPE_BLOB:
    default: {
      ulong param_length =
          get_param_length(packet, packet_left_len, header_len);
      /* in case of error ret is 0 and header size is 0 */
      *err = (param_length == 0 && *header_len == 0);
      if (param_length > packet_left_len - *header_len)
        param_length = packet_left_len - *header_len;
      DBUG_PRINT("info", ("ret=%lu", param_length));
      return param_length;
    }
  }
}
```

**Comment by harshit-gangal** [comment]
I have made changes to the decoding for `year` in binary protocol to be `varbinary`.
Need to decide if this is safe to be merged.
