### ISSUE TITLE
regex in xtrabackupengine.go

### ISSUE THREAD

**Issue by marctorresa** [vitessio/vitess#7077]
#### Overview of the Issue

In this file https://github.com/vitessio/vitess/blob/master/go/vt/mysqlctl/xtrabackupengine.go in line 619 there is a regex that works with MySQL 8 but might not work in 5.7 due to the GTID spawning multiple lines.
#### Reproduction Steps

Steps to reproduce this issue, example:

Paste the regex as you have it and ingest an XtraBackup logfile and it catches MySQL8 GTIDs but misses 5.7.

#### Operating system and Environment details

Any

**Comment by shlomi-noach** [comment]
permalink for said regexp: https://github.com/vitessio/vitess/blob/3b94d7a08473b60ac1d0974de88f022260dc0897/go/vt/mysqlctl/xtrabackupengine.go#L619

Can you please clarify why this regexp would break on 5.7 and why the problem doesn't show up on 8.0?

**Comment by marctorresa** [comment]
XtraBackup 8 outputs the GTID at the end of the backup in one line. It might be a long line but just one.

XtraBackup 2.4 outputs the GTID in multiple lines unless it is really short. I suggest you use XtraBackup 2.4 (e.g. 2.4.15) and compare the variable **xtrabackupReplicationPositionRegexp** with the GTID as shown in the XtraBackup logfile. You might see a difference ...

**Comment by shlomi-noach** [comment]
Thank you for providing details!

**Comment by enisoc** [comment]
I did experience the multi-line GTID causing problems with xtrabackup 2.4 in the past, but this fix from over a year ago has been working for us ever since: https://github.com/vitessio/vitess/commit/b56856b301045714c0f77579dfa62636ee3a44c9

In essence, the regex you linked is being matched against a multi-line string, not one line at a time. If you're testing the regex with something like grep, it is probably defaulting to single-line mode. Here's an example to show that Go's regexp library matches across lines: https://play.golang.org/p/UPNi3wP8tZF.

Can you confirm what version of Vitess you're running? The fix was merged in August 2019.

If you're using a recent version and still experiencing this problem, then we may have a regression or an additional corner case. What we look for is first a line containing the substring "MySQL binlog position". Then we capture all remaining lines of the stderr output of xtrabackup and concatenate them into one multi-line string.

Do you see "MySQL binlog position" in your log? If so, can you share a snippet of the log starting from that line onward (redacted if necessary)?

**Comment by marctorresa** [comment]
This can be closed then as a non-bug. If the input variable will always contain the whole XtraBackup logfile, then it should always work.

I raised this because I encountered this same problem of split of GTID in 2.4 vs 8 a few weeks ago in my own code. So mea culpa!

**Comment by shlomi-noach** [comment]
Thank you
