### ISSUE TITLE
Task: Cleanup references to master and slave in vt/orchestrator

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#7110]
There are several references in the code under `vt/orchestrator`. Some of them can probably be deleted outright because we don't have to worry about backwards-compatibility yet.

For example:
```
SlaveLagQuery                              string   // Synonym to ReplicationLagQuery
```
Variables, functions and parameters should be renamed.
Every occurrence should be evaluated to determine whether it can be removed. There might be exceptions like the exact text of MySQL error messages and low-level MySQL commands.

**Comment by shlomi-noach** [comment]
I have long since removed all and any `slave` reference in `orchestrator`, with the exception of:

- API calls (anything that supports `slave` also supports `replica`
- API responses (any JSON output that has "slave" also has "replica" or other compatible name)
- CLI commands (anything that supports `slave` also supports `replica`)

All the above were kept for backwards compatibility, with the advantage that no new user _needs_ to use the word `slave`.

`vorchestrator` can break backwards compatibility and we can eliminate `slave` terms altogether.

I had/have no work done for removing `master`.

**Comment by GuptaManan100** [comment]
Closing this issue, since all the required changes have been made
