### ISSUE TITLE
Task: Change TabletType MASTER to PRIMARY

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#7113]
There has been discussion in the past on exactly which term to replace `master` with. Since vitess is a consensus-based system, `primary` seems like the most appropriate choice (even though `source` is popular for replication use cases).

TabletType is everywhere in the code base, so we will need to first determine the scope of this change and how to do it in a backwards compatible way.

Website docs should be updated along with code.

**Comment by ajm188** [comment]
I _think_ that if we just rename the field in the enum, then anyone dependent on that should not notice, since it'll still be `int(1)` on the wire. Then, the code change becomes atomic; we do a global find/replace to `topodatapb.TabletType_PRIMARY`, and code compiled on the old version still works with the old field name, and code compiled on the new version works with the new field name.

**Comment by derekperkins** [comment]
There are a few edge cases where the string representation is used, specifically when json marshaling, so we'd have to check for those types of usage.

**Comment by derekperkins** [comment]
While I personally prefer `primary`, I'd vote to match MySQL and call it `source`
https://mysqlhighavailability.com/mysql-terminology-updates/
https://dev.mysql.com/doc/refman/8.0/en/replication.html

**Comment by ajm188** [comment]
> There are a few edge cases where the string representation is used, specifically when json marshaling, so we'd have to check for those types of usage.

Ah, nice catch! I think we can use an alias in that case https://developers.google.com/protocol-buffers/docs/proto3#enum (I can't link precisely enough)

**Comment by deepthi** [comment]
Fixed by #8511
