### ISSUE TITLE
Feature Request: VSchema for “Subsharding” VIndex

### ISSUE THREAD

**Issue by csquared** [vitessio/vitess#7332]
## Goal

Specify a Multicolumn VIndex that contains (at least) two parts: a “primary” sharding key and a “secondary” sharding key. This allows a sharding strategy that constrains scatter queries that include the primary or “main” sharding key to a subset of shards.

For example, given two columns `A` and `B`, with values `a`  and `b` we can construct a keyspace id like:

`hash(a)[0..N] | hash(b)[0..M]`

Which would take the first `N` bytes from the hash of `a` and concatenate that with the first `M` bytes from the hash of `b`.

## Use Cases

A common use case for Vitess is when a given entity’s data will fit on more than one shard. However, if there is not a suitable intermediary grouping construct, storing that entity’s data across all shards will lead to expensive scatter queries.

A solution is using a prefix/postfix solution, which is really a subset of a generic tree-like sharding mechanism. In this solution, a keyspace id would include information about the larger entity and then progressively include more specific sharding information.

This would allow operators to still take advantage of splitting keyspaces as designed/intended while maintaining a higher level of performance than scatter queries when both:
1. the fully qualified shard key is not known
2. maintaining a lookup vindex is also prohibitive

## Query Patterns

When a query includes just the value `a`, we would like Vitess to not scatter and instead use the computation of `hash(a)` to constrain scatter queries to only the shards on which that hash would exist.

### Fan-out (but not scatter)
For example:

` select * from customers where A = a;`

Would target N shards, but not fully scatter.

We would also expect this to work with aggregates, ie:

`select c, sum(d) from customers where A = a;` 

### Point lookup
When read or write query includes both `a` and `b`, Vitess will compute the complete Keyspace ID and deterministically route to a specific shard.

For example:

`select * from customers where A = a and B = b;`

would hit one shard

### Insertion
Insertion will use column A and B to route the request to a specific shard.

`insert into customers (A,B,C) values (a,b,c)`

## Suggested VSchemas

Names are hard. For these example VSchemas, I will call this a “subshard” index but naming rights are left to the implementor.

### Simplest
This is a suggested example of the simplest way to configure this type of VIndex:
```
    "subshard_idx": {
      "type": "subshard"
    }
```

We would use it thus:
```
    "customer": {
      "column_vindexes": [
        {
            "columns": ["A", "B"],
            "name": "subshard_vdx"
        },
```
For this use, we would:
1. be inferring the “main shard” and “sub shard” from the position of the columns within the array of `columns`.
2. allowing the implementor to determine the hash key
3. allowing the implementor to determine the number of bytes used from the hash

I believe for (1) we'll always need to rely on the position of the columns in the array, but the number of columns does not need to be fixed at 2. Defaults (2) and (3) could potentially be parameterized. Examples of each are below.

### Enhancements
Support an arbitrary number of columns:
```
    "customer": {
      "column_vindexes": [
        {
            "columns": ["A", "B", "C"],
            "name": "subshard_vdx"
        },
```

It would also be possible to configure the number of bytes used for each part of the key:
```
    "subshard_vdx": {
      "type": "subshard",
      "params": {
          "main_shard_bytes" : 10,
          "sub_shard_bytes": 10
      }
    }
```

Or in a world with more than two columns:
```
    "subshard_vdx": {
      "type": "subshard",
      "params": {
          "bytes" : 10
      }
    }
```

It would also be possible to configure the hash algorithm:
```
    "subshard_vdx": {
      "type": "subshard",
      "params": {
          "hash_func" : "xxxhash"
      }
    }
```

We can use the issue to discuss which enhancements are worth doing :)

**Comment by jmoldow** [comment]
Related Slack thread: https://vitess.slack.com/archives/C0PQY0PTK/p1608169868300000

Jordan Moldow  1 month ago
I'm wondering what is on your near- and medium-term roadmap with regards to MultiColumn vindexes. https://vitess.slack.com/archives/C0PQY0PTK/p1606778040011600?thread_ts=1606771944.004500 My understanding is that right now, the only MultiColumn vindexes are region_json (and certain lookup vindexes too?)
I'm brainstorming a VSchema for my existing non-Vitess sharded application, and thinking through whether we would need MultiColumn vindexes that don't exist yet.
But so far none of my own ideas have been very well thought-through, so I'm curious to hear what kind of MultiColumn vindexes you are thinking might be a good idea for Vitess.. and what kinds you've been presented with that you think would not be a good idea for a VSchema.

sougou
we've started implementing multi-column vindexes, but it's not quite there yet
From a thread in #general | Nov 30th, 2020 | View reply






sougou @sougou  :planetscale-dark:  1 month ago
There are two aspects to multi-column vindexes:
Is there a use case other than region for them
What additional functional features can we add for multi-column

sougou:planetscale-dark:  1 month ago
For 1., I haven't encountered a use case beyond region_json. The only non-region use case is the situation of a large tenants. But I think region_json can satisfy such use cases also (in spite of being named differently).

sougou:planetscale-dark:  1 month ago
For 2., The multi-column behavior works only at the time of insert. It will be nice if vitess could also route other queries using those values

sougou:planetscale-dark:  1 month ago
The simple use case is the one where both columns are in the where clause

sougou:planetscale-dark:  1 month ago
The more complex use case would be a partial match on just one column.

sougou:planetscale-dark:  1 month ago
The more complex use case can actually be implemented differently on existing vitess: build single column vindexes for each of those columns.

sougou:planetscale-dark:  1 month ago
So, I'm thinking we mainly need to make the use case where all column values are in the where clause work.

Jordan Moldow  1 month ago
So your comment was mainly about WHERE clause support being on the TODO list, but you don't have plans for new VIndexes.
Sharding large tenants is one thing I'm thinking about. We shard exclusively by tenant right now, but we really need to get away from that and break some/all of them up. Using region_json for more than just regions is an interesting idea. But it seems like it has some major drawbacks:
If you actually need to shard by region, seems like that would complicate your ability to implement that idea, if not make it downright impossible.
region_json only supports 2-bytes worth of return values. So it can't support more than 65536 tenants.
Even if it did support 3+-bytes, seems like it'd be challenging to maintain all the tenants in that json file and roll out updates globally as new tenants are added.
Besides sharding large tenants (though it ends up being related), the second potential use-case that I am vaguely pondering is this. In our system, we have files that belong to a parent folder, and also to the owning user. We could shard by user, but that is essentially sharding by tenant and can lead to huge shards. We could shard by the parent folder, which would work nicely in many cases. But it falls apart at the root, where we represent "root" files as having a 0 parent folder. This sharding would lead to a potentially huge, un-shardable hot spot for that one special ID. So I'm thinking if there could be something like concat(hash(folder_id),hash(user_id)) (this would still lead to un-even shard sizes for the folder_id=0 hotspot, but at least they could be partitioned into smaller shards), or something like if folder_id != 0 then hash(folder_id) else hash(user_id) (which wouldn't have that hotspot problem, and might be straightforward to have WHERE clause support for?). Something like a well-thought-out concat operator could also potenttially enable mixing region_json withtenant sub-sharding.  I'm sure there's major drawbacks to these ideas, but that's where my mind often wanders. (edited) 

Jordan Moldow  8 days ago
@sougou Wondering if you had any additional thoughts on my last message here.
I see you present another option in the new guide https://vitess.io/docs/user-guides/vschema-guide/advanced-vschema/#alternate-approach :
You have the option to pre-combine the region and id bits into a single column and use that as an input for a single column vindex. This approach achieves the same goals as a multi-column vindex. Moreover, you avoid having to define additional vindexes for query routing.
The downside of this approach is that it is harder to migrate an id to a different region.
So I guess that is your recommended approach, rather than trying to figure out a way to create additional general-purpose multi-column Vindex types in the open source Vitess?
I guess another possible approach would be to use region_json, where the region_map is an actual region map, and id column is the additional set of bits that you manually define in order to implement tenant grouping.

sougou:planetscale-dark:  8 days ago
Yeah. At this point, I don't have the confidence to recommend one way or another. I do lean towards combining the bits upfront right now.

sougou:planetscale-dark:  8 days ago
The one use case that's causing me pause is a future one: if the queries always had region and id, then we can extend vitess to use the two values to instantly to resolve the keyspace id (edited) 

sougou:planetscale-dark:  8 days ago
that would be the best of both worlds. but the functionality doesn't exist yet

Jordan Moldow  8 days ago
What happens today behind-the-scenes for handling different varieties of WHERE clauses for non-unique lookup vindexes (since they need to be MultiColumn in order for each lookup table row to have exactly one keyspace id and a unique primary key)?
If you have a unique MultiColumn vindex on A,B,C (e.g. a non-unique vindex on A), does it get treated as if it were a single-column vindex on A?
Is that why region_json has these multi-column WHERE clause cases that aren't already handled in the code?

sougou:planetscale-dark:  8 days ago
correct

sougou:planetscale-dark:  8 days ago
which is why i said this:
This may result in the merger of consistent_lookup with a multi-column version of consistent_lookup_unique that can also perform non-unique lookups on a subset of the inputs.

Jordan Moldow  8 days ago
Ah, missed that.

**Comment by jmoldow** [comment]
Most relevant quote there:

https://vitess.io/docs/user-guides/vschema-guide/advanced-vschema/#alternate-approach :

> You have the option to pre-combine the region and id bits into a single column and use that as an input for a single column vindex. This approach achieves the same goals as a multi-column vindex. Moreover, you avoid having to define additional vindexes for query routing.

>  I guess another possible approach would be to use [....] id column is the additional set of bits that you manually define in order to implement tenant grouping.

**Comment by narcsfz** [comment]
Comparing with the pre-combined column, I feel "SubSharding" VIndex provides limited fanout functionality as well. 

In the geo example, given a country, pre-combined VIndex cannot route the request to N shard - it might need fanout to all shards without a look up tablet; whereas sub-sharding can just hit N specific shards for a country.

**Comment by csquared** [comment]
This is something we were looking to get going over at Stripe, but wanted to start out with a good description of the problem for review -- thanks for your feedback, @narcsfz and @jmoldow !

It seems y'all are bullish on this idea/direction?

**Comment by jmoldow** [comment]
> It seems y'all are bullish on this idea/direction?

I'm undecided. Also, I'm early in the evaluation phase, I don't have any live Vitess clusters at the moment.

It seems there's a tradeoff here between:

- Having an architecture similar to our old one (where we sharded by tenant) but that can still support tenants that are too large to fit on one Vitess shard. And where it is easy to determine if a tenant is affected by an incident on a particular shard. This feature would be useful here.
- Having an architecture where the keyspace ranges are equally sized, because the sharding key doesn't create hotspots and all shards are able to grow at the same rate. This feature would not necessarily support this kind of architecture.

**Comment by jmoldow** [comment]
> In the geo example, given a country, pre-combined VIndex cannot route the request to N shard - it might need fanout to all shards without a look up tablet; whereas sub-sharding can just hit N specific shards for a country.

Another way to accomplish this, would be if VTGate supported the `WHERE in_keyrange()` construct (which right now, AFAIK, is only supported for VReplication and VStream).

Say we have a pre-combined Vindex column `c`, which is populated by the application as `fn(a) concat fn(b)` (and the Vindex on the combined column `c` is an `identity` vindex). Right now, without a lookup vindex, you couldn't do `WHERE a=?` without a full scatter-gather.

But if `in_keyrange()` was supported, you could do `WHERE a=? AND in_keyrange("a-next(a)")` (where `next(a)` is the next-highest hexadecimal number with the same number of hex-digits as `a`). This would scatter-gather only to the shards that cover the keyspace id prefix `a`.

Since the current syntax isn't `?` friendly, you could introduce a new syntax `WHERE in_keyrange(?)` that would do what is described above, or introduce a new function e.g. `WHERE keyrange_prefix_is(?)`.

**Comment by harshit-gangal** [comment]
RFC https://github.com/vitessio/vitess/issues/3481 looks prerequisite to this feature

**Comment by harshit-gangal** [comment]
With the PR https://github.com/vitessio/vitess/pull/9390 `region_experimental` vindex can perform subsharding vindex for 2 columns. 
I will be taking this feature on to provide a more generic approach.
