### ISSUE TITLE
Feature Request: Build/publish v9.0.0 and latest for hub.docker.com/r/vitess/vtctlclient

### ISSUE THREAD

**Issue by jmoldow** [vitessio/vitess#7399]
#### Feature Description

Publish the `v9.0.0` tag for hub.docker.com/r/vitess/vtctlclient .

On an ongoing basis (similar to what is done for `vitess/lite` and `vitess/base`), publish the `latest` tag for hub.docker.com/r/vitess/vtctlclient after merges to HEAD.

#### Use Case(s)

Being able to `docker pull vitess/vtctlclient:$version` and `docker run vitess/vtctlclient:$version` on your local development computer, for easy switching between versions, instead of having to install go and build the client manually for each new version.

This Docker image is much more compact than the `vitess/lite` and `vitess/base` images, which are multiple GB and take a long time to download onto a local development computer without a blazing fast internet connection.

Also, I'm thinking that `vitess/vtctlclient` could be used as the image for a Kubernetes `CronJob` to issue `BackupShard` commands.

**Comment by deepthi** [comment]
I have updated the configuration on dockerhub. There should be a `latest` build soon-ish.
Yet to figure out to trigger a build on a branch without pushing to it.

**Comment by deepthi** [comment]
I have pushed a `v9.0.0` image. Please try it out and let me know if it doesn't work.

**Comment by jmoldow** [comment]
Thank you @deepthi ! I was able to `docker pull` the `latest` and `v9.0.0` tags.

There seem to be other images that are in the same boat that `vtctlclient` used to be in:
```
jmoldow@mbp-010199 k8s ((HEAD detached at origin/release-9.0)) $ ls
Dockerfile	logrotate	logtail		mysqlctld	orchestrator	pmm-client	vtbackup	vtctl		vtctlclient	vtctld		vtexplain	vtgate		vttablet	vtworker
```

Most of these (besides `vtexplain` and now `vtctlclient`) haven't been updated since `v8.0.0`. I don't know what the use-cases of these images are (since I believe `lite` contains most/all? of these components), so I don't know if you intentionally stopped publishing to them, or if they also need to be fixed like you fixed `vtctlclient`.

**Comment by deepthi** [comment]
I'm not sure what the history is, and why specifically after 8.0.0 they stopped getting updated.
Maybe @dkhenry knows, otherwise I will look into it.
Historically a lot of these "small" images were used by helm charts. Maybe they aren't required now that helm charts have been deprecated.

**Comment by jmoldow** [comment]
Confirmed that I can `docker run vitess/vtctlclient:v9.0.0` and issue commands successfully to my `vtctld` service.

**Comment by derekperkins** [comment]
> I'm not sure what the history is, and why specifically after 8.0.0 they stopped getting updated. Historically a lot of these "small" images were used by helm charts. Maybe they aren't required now that helm charts have been deprecated.

I forgot to push them when 9.0 was released. 😬 The history is that they predate Vitess actually cutting any releases, so I starting tagging them manually with "helm" tags since the project went years without official releases. There's a bash script here that does it https://github.com/vitessio/vitess/blob/master/helm/release.sh. Then the planetscale operator was released and started using the lite images, which to be honest I have no idea what they contain. There are people using the old images, as it has come up before in Slack, though I don't know how many. It would be really nice to consolidate how docker files are managed in the repo. There have been a lot of cooks in the kitchen not trying to step on each other's toes. :)

**Comment by derekperkins** [comment]
> Also, I'm thinking that vitess/vtctlclient could be used as the image for a Kubernetes CronJob to issue BackupShard commands.

That's exactly what it was used for in the helm charts: https://github.com/vitessio/vitess/blob/master/helm/vitess/templates/_cron-jobs.tpl

**Comment by derekperkins** [comment]
Regarding #7401 and vtexplain, that didn't exist when I made the original `docker/k8s` directory, which is why its Dockerfile is different from the others. Whoever put it in there probably didn't want to mess anything up with the `k8s` tag, so it pulls directly from `base` rather than building off of `k8s` like the rest of the images in that directory.

Side note, `lite` is a terrible name and we have had questions in the past if they are truly getting the full version of Vitess.

**Comment by deepthi** [comment]
I'm going to close this issue now that we have auto-build setup on dockerhub. I've opened #7433 to track some of the questions/concerns raised here and in #7401.
