### ISSUE TITLE
Notify VTGate when a vttablet restarted

### ISSUE THREAD

**Issue by sonne5** [vitessio/vitess#7954]
#### Feature Description
VTGate will periodically refresh tablets from topo server given a keyspace/shard. If a tablet crash'd, the healthstream will be closed. After the tablet is back online VTGate will only know that after the next refresh from the topo server.

This is fine for new tablet being added as a replica, there is no harm other than starting serving traffic a few min late. However, this could be a problem if we put an external reprent process into the picture. For example, say a 3-node shard: A (primary), B and C.

t1: B tablet process crashed and VTGate close connection with it
t2: B's tablet process restarted and back normal
t3: node A crashed, the external reparent process kicked in and elect B as the new primary

Now if the VTGate does not refresh the topo server between t2 and t3, the requests will fail at VTGate layer even if we have a healthy shard underneath.

Thinking out loud a potential solution: since the number of VTGate is way larger than the number of VTTablet, topo server might be a good centralized place to communicate this between VTGate and VTTablet through a watch. If there is a update a the primary tablet, update the node in topo server to trigger a refresh in VTGate so that it can pick up new primary as soon as possible

#### Use Case(s)
See the description above

**Comment by narcsfz** [comment]
cc @deepthi just put this on your radar

**Comment by deepthi** [comment]
When there is an error from the health stream connection, vtgate does not "forget" the tablet. It simply retries after a delay (which we exponentially back off).
It is possible that depending on how long the tablet is down, the delay could get large enough.
So I'm not sure exactly why you are seeing what you are seeing, but it is not because vtgate has forgotten the tablet.
There are only two conditions under which a tablet is "deleted":
* It has been removed from the topo
* The host:port has been taken over by a different tablet

**Comment by narcsfz** [comment]
@deepthi thanks for chime in and clarifying.

I think the communication between VTTablet and VTGate is through the health stream. I might still miss something, the backoff retry logic can have up to 1 min interval to recreate the stream connection, which means there will be up to 1 min downtime after the tablet process is up and running and serve as the primary tablet.

If VTTablet can force VTGate to recreate connection after a tablet is back on line especially if it serve as the primary, it should notify VTGate and make sure the health stream is up and running

**Comment by narcsfz** [comment]
Just to clarify the idea: it's not having VTTablet notifies VTGate through an extra request but letting VTTablet update topo server and VTGate get notified by watching a specific topo path.

I know we are trying to remove the dependency of topo server, but in this case, it's an optimization instead of adding an hard dependency on topo server.

**Comment by deepthi** [comment]
Communicating the primary to vtgate via topo has been tried and found to be slower than relying on the healthcheck stream.
Adding watches on each tablet record in each vtgate when there maybe thousands of vtgates is also not scalable.

I understand that the situation here is a combination of two events:
(a) tablet restart
(b) restarted tablet immediately promoted to primary

To mitigate these situations, orchestrator has logic to avoid electing a new replica as primary (though that is at the mysql level). You might consider something like that (since you do have another healthy replica).
Other option is to reduce the healthCheckTimeout from it's default value of 1 minute.

**Comment by aquarapid** [comment]
Closing after offline discussion in light of Deepthi's update above.
