### ISSUE TITLE
Parser does not fail on invalid query

### ISSUE THREAD

**Issue by shlomi-noach** [vitessio/vitess#8057]
Based on https://github.com/vitessio/vitess/issues/8055

The following query:
```sql
alter table corder zzzz zzzz zzzz
```
should fail parsing. However, it parses without error, and on top of that, claims `isFullyParsed() == true`.

**Comment by shlomi-noach** [comment]
On vitess:
```sql
mysql> set @@ddl_strategy='direct';
Query OK, 0 rows affected (0.00 sec)

mysql> alter table corder zzzz zzzz zzzz;
Query OK, 0 rows affected (0.01 sec)
```

On MySQL:
```sql
mysql> alter table demo zzzz zzzz zzzz;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'zzzz zzzz zzzz' at line 1
```

**Comment by shlomi-noach** [comment]
I traced the problem down to this path:

https://github.com/vitessio/vitess/blob/9cc166fabc05239edd1de4c135fd21c4f34f7ce9/go/vt/sqlparser/sql.y#L1869-L1871

**Comment by shlomi-noach** [comment]
`alter_commands_list` allows just about anything. I'm not sure why that happens. The following query is also valid:

```sql
alter table corder zzzz zzzz zzzz remove partitioning;
```

in this path:

https://github.com/vitessio/vitess/blob/9cc166fabc05239edd1de4c135fd21c4f34f7ce9/go/vt/sqlparser/sql.y#L2052-L2058

**Comment by shlomi-noach** [comment]
I also notice this line gets executed on such invalid SQL:

https://github.com/vitessio/vitess/blob/9cc166fabc05239edd1de4c135fd21c4f34f7ce9/go/vt/sqlparser/parser.go#L84

Other samples of wrongly accepted syntax:

```sql
alter table corder engine=innodb zzzz zzzz;
alter table corder drop column c zzzz zzzz;
```

**Comment by GuptaManan100** [comment]
`alter_command_list` does not allow anything, it allows empty values. In the input `alter table corder zzzz zzzz zzzz` only `alter table corder` part is used in parsing and the remaining `zzzz zzzz zzzz` is not. alter_commands_list takes an empty value. 

Similarily, in the input `alter table corder zzzz zzzz zzzz remove partitioning;` only the initial part is used, the remaining parts `zzzz zzzz zzzz remove partioning` is not used. This can be seen from the AST node produced in the end, had it gone down the path https://github.com/vitessio/vitess/blob/9cc166fabc05239edd1de4c135fd21c4f34f7ce9/go/vt/sqlparser/sql.y#L2052-L2058 then the `PartitionSpec` field would not be null, but it is. 

The reason that this behavior happens is that when the parser sees the `zzzz` token, it does not match a keyword and there is no rule to accept an id. It keeps on reducing all the way to the top of the stack and the remaining input is left unused i.e the parsing is finished but there are tokens left. This can be seen from the `lasttoken` field of the tokenizer which is set to `zzzz` instead of empty string

**Comment by GuptaManan100** [comment]
I think the error lies in the lines https://github.com/vitessio/vitess/blob/9cc166fabc05239edd1de4c135fd21c4f34f7ce9/go/vt/sqlparser/parser.go#L81-L83. reading the error message, it seems that these lines should be catching the case where there is input which has not been used. The `lastError` field of the tokenizer indead shows that there is a syntax error at position 24 near `zzzz`. These lines do not catch this error and the errors are ignored in the subsequent lines. As to why tokenizer.Scan() returns 0 in these lines is still left to investigate

**Comment by shlomi-noach** [comment]
> Since only the initial tokens are used in parsing, the query becomes valid and therefore FullyParsed is set to true

I think "only the initial tokens are used in parsing" necessarily implies that `FullyParsed` should be set to `false`. What do you think?

**Comment by shlomi-noach** [comment]
Yes, that makes sense to me!

**Comment by shlomi-noach** [comment]
It's funny though that `Parse2` is not specific to DDLs though.

**Comment by GuptaManan100** [comment]
Yes, it isn't but we set the PartialDDLs only for DDLs, so it should be okay. I'll get the PR ready ASAP

**Comment by shlomi-noach** [comment]
Fixed by https://github.com/vitessio/vitess/pull/8094
