### ISSUE TITLE
Non-optional `sql_log_bin=0` in `PopulateMetadataTables` leads to error on external tablets without SUPER privileges

### ISSUE THREAD

**Issue by aquarapid** [vitessio/vitess#8505]
PR #8107, specifically 6d9af98f6a462163c5cd6b04cff6a2c8b5820834 introduced a `SET @@session.sql_log_bin = 0` command when creating the metadata tables.  While this is fine, it should somehow be optional, so we can deal with cases where the backend database is on a server (e.g. Aurora) where we do not have SUPER privs, and this will not work, and results in an error like:

```
PopulateMetadataTables(.....) failed: Access denied; you need (at least one of) the SUPER privilege(s) for this operation (errno 1227) (sqlstate 42000) during query: SET @@session.sql_log_bin = 0
```

Not having metadata tables when running with external tablets where we do not manage failover is probably not (immediately) fatal, but we're adding more to this as we go along, so we should probably fix this.

**Comment by ajm188** [comment]
Agreed we should make this optional (this was actually always true of the metadata feature: https://github.com/vitessio/vitess/pull/8107/files#diff-a8cd4d4b36ace0378cacef4b04a4b372412712a032334c0b2ca6f0ef9237fd76R106-R108). I was talking with @deepthi and what we probably want to do is start treating the `-init_populate_metadata` flag as it is intended and not named, which is to say when not set, vttablet should not manage the `local_metadata` table _at all_ (and we should also rename the flag to reflect what it's actually for), since it seems like that's not compatible with RDS or other more managed databases.

Another approach would be to require the user to configure replication to not replicate that table, and remove the `sql_log_bin=0` setting on the connection.
