### ISSUE TITLE
Trim cached schema version for schema tracking

### ISSUE THREAD

**Issue by 5antelope** [vitessio/vitess#8585]
#### Feature Description
Based on my understanding, when we enable the schema tracking feature, the historian store all the DDL for _all_ the tables in this shard into `_vt.schema_version` table (it seems like we are storing the final `CREATE TABLE` statement instead of the `ALTER TABLE`, but I think they both apply to the issue here)

When there is a DDL, historian will load top 10K schemas from `_vt.schema_version` table and keep appending to `schemas` slice: https://github.com/vitessio/vitess/blob/cb054384781ce1b89b49e68c29d23bfb0d8a190e/go/vt/vttablet/tabletserver/schema/historian.go#L167-L181

Now image a shard has multiple schema migration, the schema slice can easily fill in all the memories. There seems to be 2 optimization we can do:
1. instead of blindly append into the slice, we can do some deduping to same space
2. we don't really need _all_ the schemas, we just need the schema that is as old as `gtid_purged` - anything older than that is no longer available in binlog already

**Comment by sonne5** [comment]
cc @aquarapid this is the issue we discussed today, please correct me if I missed something and this turns out to be a red herring. thanks!

**Comment by aquarapid** [comment]
We actually only store the DDL for the schema update in the `schema_version.ddl` field, so from a memory point of view that is probably not a big deal.  However, we do store the complete schema in protobuf format in the schema_version.schemax` field.   I don't think this is a huge deal in most situations, unless your schema is truly large (many thousands of tables).

However, your point that this table can be cleaned of schemas older that gtid_purged is well taken;  doing this might be somewhat complicated;  I guess as a stopgap;  a user can put an external process/script in place to purge the file of all rows older than X days, where X is well above their binlog retention period?

**Comment by sonne5** [comment]
thanks @aquarapid. Yeah, `schemax` is basically the db schema. 

re: memory usage: putting `gtid_purged` aside, the memory usage also depends on the frequency of schema migration. On every DDL, the current logic will load 10K row and append. this means we will have a lot of duplicated schema in the `schema` slice over the time (e.g., if I do 5 DDL, the slice will keep 1 + 2 + 3 + 4 + 5 = 15 items instead of 5). This might make the search by gtid/position in the slice slower

**Comment by aquarapid** [comment]
Point taken;  but you would also need to deal with subtractive DDL;  i.e. how do you represent a drop table in the `schemax`?  So you would need to implement a diffing setup.

**Comment by sonne5** [comment]
Just to clarify, I was thinking about trim what we load in memory instead of what is in the schema_version table. It wasn't super clear to me the implication of subtractive DDLs. My understanding is we are storing the final table schemas, which means if we drop a table, we would get one less table in `schemax` - as long as we load enough schema that covers all the binlog events, we should be safe here?

**Comment by indera-shsp** [comment]
IMO a more compact storage of the data can potentially reduce the memory usage 

```
desc schema_version;
+--------------+------------------+------+-----+---------+----------------+
| Field        | Type             | Null | Key | Default | Extra          |
+--------------+------------------+------+-----+---------+----------------+
| id           | int(11)          | NO   | PRI | NULL    | auto_increment |
| pos          | varbinary(10000) | NO   |     | NULL    |                |
| time_updated | bigint(20)       | NO   |     | NULL    |                |
| ddl          | blob             | NO   |     | NULL    |                |
| schemax      | longblob         | NO   |     | NULL    |                |
+--------------+------------------+------+-----+---------+----------------+
```


```
pos_1 =>  Table_a => version_1 ==> structure
pos_2 => Table_a => version_2 ==> structure
pos_3 => Table_b => version_1 ==> structure
```

so when the historian loads we store in RAM an ordered list of versions for each table

**Comment by rohit-nayak-ps** [comment]
Fixed via https://github.com/vitessio/vitess/pull/13056
