### ISSUE TITLE
New MoveTables syntax has resulted in old syntax not working anymore

### ISSUE THREAD

**Issue by aquarapid** [vitessio/vitess#8644]
AFAIK, the intention was that (for now) the old MoveTables syntax should continue working.

However, the following simple `MoveTables` command against `vtctld` using the old syntax is not functional anymore:

```
$ vtctlclient -server localhost:15999 MoveTables -workflow=workflow1 sourcekeyspace targetkeyspace t1
flag provided but not defined: -workflow
Usage: MoveTables [-cells=<cells>] [-tablet_types=<source_tablet_types>] -workflow=<workflow> <source_keyspace> <target_keyspace> <table_specs>
...
...
```

This definitely used to work just fine.

The new (equivalent) syntax of:

```
$ vtctlclient -server localhost:15999  MoveTables -source sourcekeyspace -tables 't1' Create targetkeyspace.workflow1
```

**does** work.

Version:

```
Version: 12.0.0-SNAPSHOT (Git revision 0da8fe09c5 branch 'main') built on Wed Aug 18 14:47:58 PDT 2021 by jacques@dhoomdeskw.localdomain using go1.16.3 linux/amd64
```

Built of of main branch today.

**Comment by mattlord** [comment]
I don't think it's documented yet (?)... but you have to specify the -v1 flag:
```
vtctlclient -server localhost:15999 MoveTables -v1 -workflow=workflow1 sourcekeyspace targetkeyspace t1
*** The MoveTables v1 flow is deprecated, consider using v2 commands instead, see https://vitess.io/docs/reference/vreplication/v2/ ***
MoveTables Error: rpc error: code = Unknown desc = node doesn't exist: /vitess/global/keyspaces/targetkeyspace/VSchema
E0818 18:14:10.228788   43025 main.go:76] remote error: rpc error: code = Unknown desc = node doesn't exist: /vitess/global/keyspaces/targetkeyspace/VSchema
```

**Comment by aquarapid** [comment]
Correct;  but while the new commands are experimental, the old ones should work without change, so scripts and runbooks can continue to work unchanged.

**Comment by mattlord** [comment]
Ah, OK. I thought that the v2 workflow was the default, GA, and recommended starting with v11. I remembered seeing this, but reading it again I can see that I was wrong in various ways 😄: https://github.com/vitessio/vitess/pull/8527

I would also much prefer we don't require `-v1` as then we're not (as you noted) breaking people's workflows and tooling built around them when they upgrade to v11+ (I also ran into this not too long ago when testing the v11 `vtctl` client). I'd much rather we simply show the deprecation warning when they're used so that while not breaking anything we raise awareness of v2 and hopefully it gets more usage.

**Comment by deepthi** [comment]
v2 is the new default and `-v1` is required if you want to use the old commands.
I realize now that we should have socialized this more (and started deprecating v1 earlier).

**Comment by deepthi** [comment]
Per discussion with @aquarapid @mattlord and @rohit-nayak-ps we will not rollback making v2 the default. @mattlord is working on a docs PR to update the website reference to be in-line with the code changes.
https://github.com/vitessio/website/pull/806
