### ISSUE TITLE
Reduce performance impact of consistent snapshot during vreplication copy phase

### ISSUE THREAD

**Issue by aquarapid** [vitessio/vitess#8754]
Currently, the copy phase of vreplication has only one knob to limit its performance impact:
`-vreplication_copy_phase_duration`.  This allows adjusting the maximum duration a single consistent snapshot of the source table will run for.

However, if migrating data, upstream systems where MoveTables are running from can be very busy (high write rate), and even if the copy phase duration is limited, a lot of undo records can be accumulated because of the consistent snapshot.

One additional way to limit the snapshot impact would be to structure the copy as explicit ranges of the primary key, instead of the current (paraphrased):
```
SELECT * from table1 where pk > xxxx;
```
something like:
```
SELECT * from table1 where pk > xxxx and pk < yyyy;
```

This way, no undo records would need to accumulate during most of the copy, if the table is like most, and the writes are towards the end of the primary key range.

Obviously, implementing this is somewhat non-trivial:
  * Need to sample or make assumptions about the PK distribution
  * Need to estimate appropriate ranges (not too small, not too big)
  * Need to keep track of this information (unless we re-estimate every time the stream starts;  may be reasonable)

One simplifying solution may be to only support this "optimized impact" type copy for tables with integer PKs.

**Comment by shlomi-noach** [comment]
#8056 took a step towards this by capping the range with max existing PK, evaluated once per workflow. The request here is more similar to how `gh-ost` does this: to copy a range we run two queries: one to evaluate "what's the PK/UK at 1000 (or whatever) rows from current point", and then "select where PK/UK > current point and PK/UK <= next point which we just evaluated".

The first of these queries is done with `limit 1000` and I'm actually not sure whether InnoDB would or would not in fact hold a snapshot only for those 1000 rows.

**Comment by rohit-nayak-ps** [comment]
Some working thoughts on this. Cc @shlomi, @sougou

### Copy Phase Recap

The copy phase works by taking a `consistent snapshot` which selects *all* rows after the last primary key (`lastPK`) seen by a previous copy loop.  A long-running row streaming phase starts. Streaming is done in batches, the number of rows in a batch fit into (roughly) the `vstream_packet_size`. This streaming continues until one of:
* `-vreplication_copy_phase_duration` is reached. In this case the `lastPK` is recorded in `_vt.copy_state` and another iteration, starting from the `lastPK`, will start after a `catchup` phase ` OR 
* until all rows in the snapshot are sent, signalling the end of the copy phase for that table. The row for this table is deleted from `_vt.copy_state` and copy starts for one of the remaining tables, if any.


###  Performance impacts

The issue we are discussing here is due to concerns from the long-running consistent snapshot. The concerns are different if one is streaming from the primary or from a replica. Streaming from the primary happens usually when we migrate data from an external source like Aurora into Vitess where we have less control over the mysql resource characteristics. On the primary, we could end up with degradation of write performance and, on the replica, with high mysql replication lag. The main cause, at least on the primary, is to do with the accumulation of undo logs and/or gap lock contention. 

#### Undo Logs

The Multi-version Concurrency Control (MVCC) in InnoDB (https://blog.jcole.us/2014/04/16/the-basics-of-the-innodb-undo-logging-and-history-system/) can create a lot of undo logs (~ _history list_) if there is a large write qps to the table being copied. This can potentially cause significant deterioration in write performance.

How can we quantify this? `show engine innodb status;` outputs lines like
```
History list length 19
```
```
3827 lock struct(s), heap size 549072, 400782 row lock(s), undo log entries 398869
MySQL thread id 1076458, OS thread handle 140256454616832, query id 5878584 localhost msandbox
```
We have a single summary report of the history length and size of undo log entries but not per table.

#### Gap Locks
InnoDB holds locks on any index pages straddling the rows in the consistent snapshot (https://dev.mysql.com/doc/refman/5.6/en/innodb-locking.html#innodb-gap-locks). This can cause higher latencies while inserting new rows if the index pages that need to be updated as part of the insert are already locked. 

`show engine innodb status;` outputs per-transaction lines like
```
---TRANSACTION 72C, ACTIVE 755 sec
4 lock struct(s), heap size 1248, 3 row lock(s), undo log entries 1
MySQL thread id 3, OS thread handle 0x7f84a78ba700, query id 163 localhost msandbox
TABLE LOCK table test.t trx id 72C lock mode IX
RECORD LOCKS space id 19 page no 4 n bits 80 index age of table test.t trx id 72C lock_mode X
RECORD LOCKS space id 19 page no 3 n bits 80 index GEN_CLUST_INDEX of table test.t trx id 72C lock_mode X 
locks rec but not gap
RECORD LOCKS space id 19 page no 4 n bits 80 index age of table test.t trx id 72C lock_mode X 
locks gap before rec
```
The last line reports a gap lock for a table, but it is per transaction and hence we will need to parse every transaction.

`show engine innodb status` outputs loosely structured text. It looks parsable and used by many for monitoring, but will it be brittle: can mysql versions, global settings affect the output format? Also, for high qps systems, the output might be huge. 

Maybe the `performance_schema` in newer MySQL versions contains some of these metrics?

## Potential Solutions

The current approach of tuning using `-vreplication_copy_phase_duration` to reduce the time the snapshot is held has several issues:
* it is a vttablet flag and thus applies for all running workflows
* it applies for all tables in a workflow independent of the actual load on them
* gap lock contention may continue to cause issues since we will start a new snapshot soon after the previous ends
* undo logs sizes might still cause an issue since history records would have been created for all rows in each snapshot even though only a few rows are actually copied and mysql doesn't purge these logs very often

So it would be good to lock just the range of rows that will be streamed each time. I initially wondered if we can just use the `limit` options as part of the snapshot queries, but, per Shlomi, the EXPLAINs of queries with or without limits show the same execution plan.

The approach suggested in this issue is of limiting the range by computing an upper limit for the lastPK. However as mentioned it is non-trivial: different (esp non-numeric) data types in the PK, holes in the PK ranges, widely differing row sizes across tables etc. We could create some special cases: only handle simple integral PKs and adapt based on sampling or previous runs etc. We need to weigh the benefits vs the additional complexity/potential randomness it can generate. We definitely need a testbed to reproduce such issues and benchmark implementations. 

The current thought is that we should prefer adaptively limiting the copy loop time rather than using row ranges. Also to explore the feasibility of a system metric to inform the adaptive algorithm.


#### Aside: Issue with multiple copy loops
This is just to note an implementation detail that we will need to address for any of the above methods. Currently each copy loop for a table expects that it will only end with a timeout or when it is completed. This makes it easy to decide when the table copy has completed. 

However if we now limit the copy loop either by time or by number of rows we need to decide which loop is the last one. If a table is being continually inserted into then we will never end up reading *all* rows. Shlomi has partially implemented a solution to this in an experimental PR. The idea is to compute the maxLastPK at the start of the first copy loop, record that in `_vt.copy_phase`, modify the rowstreamer RPCs to expect this in every call and only stream rows upto the maxLastPK.

**Comment by mattlord** [comment]
I'm going to start spending some time on this. I will start by exploring two options, with a focus on reducing the impact on the source and NOT on increasing the operation performance / completion times:
1. Some ways to limit the gap locks we take, especially on infimum and supremum
2. Some form of adaptive backoff/pause in between copy phases that takes the source's history list length into account

**Comment by rohit-nayak-ps** [comment]
We have already done stuff that can be done safely. We can revisit if required.
