### ISSUE TITLE
Go Get Deprecated

### ISSUE THREAD

**Issue by zek** [vitessio/vitess#8782]
#### Overview of the Issue

I'm a newbie to Vitess and trying to migrate my existing production database.
Trying to test migration existing local database to remote kubernetes server.
However I couldn't install latest version of vitess locally. 
brew formula version is 10.0.2 and go get command is deprecated.

#### Reproduction Steps

`go get vitess.io/vitess/go/cmd/vtctlclient`

#### Binary version

Version: 10.0.2 (Git revision  branch '') built on Sat May 29 06:27:23 BST 2021 by brew@BigSur using go1.16.4 darwin/amd64

#### Operating system and Environment details

OS, Architecture, and any other information you can provide
about the environment.

- Operating system macOS Big Sur
- Kernel version Darwin 20.3.0
- Architecture arm64

# Logs

```
go get: installing executables with 'go get' in module mode is deprecated.
	Use 'go install pkg@version' instead.
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
```

**Comment by zek** [comment]
Would be awesome if you can share the instructions to migrate data from local database to remote kubernetes server. In my case I can't stop my production database for data migration guess I need to use movetables.  

I've already installed operator and Bring up an initial cluster

```
kubectl apply -f operator.yaml
kubectl apply -f 101_initial_cluster.yaml
```

Thanks in forward.

**Comment by askdba** [comment]
First of all, thank you for asking questions. Some of these may be easier to ask in the Vitess Slack channel.

Let's get your local install working first. 
Assuming you already have `homebrew` can you just run this on your Mac? 
```brew install vitess```

This should install `Vitess` on /usr/local/share/vitess. Documented here https://vitess.io/docs/get-started/local-brew/

So part II of your question if you are migrating over to K8s cluster from your local or another source the best way to set up external tablet workflow from your original cluster. I don't think we have documented steps to do it but in summary, link your K8s cluster to this local instance. I'd recommend doing it from your Cloud provider's VM instead of doing it from your local. This way port forwarding and allow lists for IP addresses are easier. 

For this please review https://vitess.io/docs/concepts/move-tables/
and https://vitess.io/docs/user-guides/migration/move-tables/ with examples. 
We'll try to get a demonstration of this as time permits.

**Comment by deepthi** [comment]
Homebrew has not published a new formula for vitess 11.0.0. The PR for it was closed without merging https://github.com/Homebrew/homebrew-core/pull/81984
They reported #8554 as an issue that is preventing this, however the way to fix it is for them to fix their unit tests.
One of us needs to either follow up with the homebrew team, or do a PR against the homebrew repo to fix the unit test that is blocking this upgrade.

**Comment by mattlord** [comment]
Trying to address the homebrew issue here: https://github.com/Homebrew/homebrew-core/pull/88725

**Comment by mattlord** [comment]
I'm closing this as fixed via https://github.com/Homebrew/homebrew-core/pull/88725 for now. If I missed something please let me know and we can re-open it. Thanks!
