### ISSUE TITLE
VTTablet heartbeat write should use DBA connection

### ISSUE THREAD

**Issue by sonne5** [vitessio/vitess#9010]
#### Feature Description
When vttablet creates a heartbeatWriter, it takes connection parameters for both vt_app and vt_dba. However, when execute CREATE TABLE statement, it always uses vt_app: https://github.com/vitessio/vitess/blob/main/go/vt/vttablet/tabletserver/repltracker/writer.go#L173

We should use vt_dba for the `CREATE TABLE` statement, and vt_app user for the actual insert/update

**Comment by sonne5** [comment]
cc @aquarapid @mattlord

**Comment by GuptaManan100** [comment]
@sonne5 The PR that made the change #9033, actually created another issue with PRS. The issue is described in detail in #9290. TL;DR, the `vt_dba` user has the super privilege which allows it to run commands even when the underlying MySQL instance is set to read only. This causes the old primary to diverge from the new primary when we perform a PRS.

Keeping this in mind, we have reverted the change to the user in the heartbeat writer for now back to `vt_app`. The PR that makes that change is #9299. 

Is there a specific reason why you wanted to use the `vt_dba` user for the creation of table and database? `vt_app` has the CREATE privilege as seen in the `init_db.sql` file.

Also, as far as the pool was concerned, it was only using the `vt_dba` to kill the queries which were running longer than the set timeout

**Comment by sonne5** [comment]
We don't grant `CREATE` privilege to `vt_app` user hence the change in https://github.com/vitessio/vitess/pull/9299 will break our integration.

+1 to what @deepthi suggested here https://github.com/vitessio/vitess/issues/9290#issuecomment-982813381 , it seems a bit risky to assume the privilege for `vt_app` user here - for example, i'm under the impression (incorrectly) that `vt_app` was meant to used by requests from vtgate and not being used by heart beat by design :-) I think the short term workaround might be using `vt_allprivs` to do the heartbeat write here?

cc @aquarapid

**Comment by deepthi** [comment]
thanks @sonne5 we'll go back to the drawing board and figure out how to fix this properly.

**Comment by GuptaManan100** [comment]
@sonne5 I have made the required changes in https://github.com/vitessio/vitess/pull/9320
