### ISSUE TITLE
ReloadSchemaKeyspace is slow

### ISSUE THREAD

**Issue by dasl-** [vitessio/vitess#9984]
### Overview of the Issue

In v12, when calling `ReloadSchemaKeyspace`, the `-concurrency` flag is not respected. It will reload the schema on each shard serially: https://github.com/vitessio/vitess/blob/2e02f0d99b27a857358e42baac73cf44e4918cbb/go/vt/wrangler/schema.go#L125-L127

We might expect it to parallelize the reloading with our specified `-concurrency` across all shards, rather than across all tablets per shard. Because of this issue, `ReloadSchemaKeyspace` will take about 8 hours to finish on our cluster.

It looks like this issue might be fixed in v13? https://github.com/vitessio/vitess/blob/2b5f72c5dd0411c3ff9da4517c4a8d32c4f57fc5/go/vt/vtctl/grpcvtctldserver/server.go#L2144-L2157

### Reproduction Steps

Call `vtctl ReloadSchemaKeyspace`

### Binary Version

```sh
Version: 12.0.3 (Git revision 12.0.57-5.10e08bd.el7.centos branch 'etsy-12.x') built on Thu Mar  3 13:27:24 UTC 2022 by builder@9675f2def909 using go1.17.5 linux/amd64
```

### Operating System and Environment details

```sh
Linux 3.10.0-862.3.2.el7.x86_64
```

**Comment by mattlord** [comment]
Hi @dasl-!

I'm not sure why this wasn't done in a goroutine originally but we did parallelize this work in v13 via: https://github.com/vitessio/vitess/pull/8012

Just FYI, you can also eliminate the need for (most) manual `ReloadSchemaKeyspace` calls by leveraging the Schema Tracking feature in v12 and later:
- https://vitess.io/docs/12.0/reference/features/schema-tracking/
- https://vitess.io/blog/2022-01-11-schema-tracking/
- https://vitess.io/docs/12.0/design-docs/vreplication/vstream/tracker/

I'm going to close this as fixed for now, but please let me know if I missed or misunderstood something.

Thanks!

**Comment by deepthi** [comment]
@mattlord did you intend to link a different PR? #8012 is present in 11.0+

**Comment by mattlord** [comment]
Sorry, I must have gotten my wires/tabs crossed. This is the PR where we parallelized the shard calls as part of moving these functions from the wrangler to vtctldserver in v13: https://github.com/vitessio/vitess/pull/8832

In this case, however, I suspect the combination of the high number of shards in the keyspace, with each shard having a very high number of tables, with MySQL 5.7 being used, with a slow I_S query that was likely the larger issue: https://github.com/vitessio/vitess/pull/9632

There's a separate discussion about how to address this specific case and since as much as this may be considered a bug it's been resolved in main, I closed the ticket. Should have removed the triage tag too though... TGIF! 😃
